import React from 'react';
import Head from 'next/head';
import Page1 from "./Page1"
import Page2 from "./Page2"
import Page3 from "./Page3"
import Page4 from "./Page4"
import Footer from "../../components/footer"
export async function getStaticProps() {
  const res = await fetch(
    'https://syncrow.kodagu.today/api/efficiency?populate[0]=page1_cover.media&populate[1]=page3_cover.media&populate[2]=page4_cover.media&populate[3]=efficiency_list_item'
  );
  const response = await res.json();
  var data = response.data.attributes;
  return {
    props: {
      data,
    },
  };
}
export default function Efficiency({ data }) {
  const guthen = 'Guthen Bloots Personal Use';

  return (
    <div className='overflow-x-hidden'>
      <Head>
        <title>Syncrow</title>
        <meta name='description' content='Generated by create next app' />
        <link
          rel='icon'
          href='https://ik.imagekit.io/jason7531/syncrow/common/Group_1_rkAObjd65.png?ik-sdk-version=javascript-1.4.3&updatedAt=1642343317149'
        />
        <style>
          @import
          url(https://fonts.cdnfonts.com/css/guthen-bloots-personal-use);
        </style>
      </Head>
      {/* < page1 > */}
     <Page1/>
        {/* page2 */}
        <Page2/>
      {/* page3 */}
      <Page3/>
        {/* page4 */}
       <Page4 />
           <Footer />
    </div>
  );
}
