import Header from '../../components/header';
import Footer from '../../components/footer';
import Link from 'next/link';
import Head from 'next/head';
import parse from 'html-react-parser';
import Page1 from "./Page1"
import Page2 from "./Page2"
import Page3 from "./Page3";
import Page4 from './Page4';
export async function getStaticProps() {
  const res = await fetch(
    'https://syncrow.kodagu.today/api/iot?populate[0]=page1_cover.media&populate[1]=page2_cover.media&populate[2]=page3_cover.media'
  );
  const response = await res.json();
  var data = response.data.attributes;
  return {
    props: {
      data,
    },
  };
}
export default function IOT({ data }) {
  const guthen = 'Guthen Bloots Personal Use';
  return (
    <div className='overflow-x-hidden'>
      <Head>
        <title>Syncrow</title>
        <meta name='description' content='Generated by create next app' />
        <link
          rel='icon'
          href='https://ik.imagekit.io/jason7531/syncrow/common/Group_1_rkAObjd65.png?ik-sdk-version=javascript-1.4.3&updatedAt=1642343317149'
        />
        <style>
          @import
          url(https://fonts.cdnfonts.com/css/guthen-bloots-personal-use);
        </style>
      </Head>

      {/* page1 */}
      <Page1 />
      <div
        className="tablet:mx-8  w-[100%] mx-8 mt-10 tablet:mt-28">
        <img src="/IOT-page-1.png" alt="..." className="bg-red-400 w-[95vw] object-cover" />
      </div>
      {/* page2 */}
      <Page4 />
      {/* page3 */}
      <Page3 />
      <Page2 />
      <Footer />
    </div>
  );
}
