import Header from '../../components/header';
import Footer from '../../components/footer';
import Head from 'next/head';
import { motion } from 'framer-motion';

export default function Industry({ data }) {
  const guthen = 'Guthen Bloots Personal Use';
  return (
    <div className='overflow-x-hidden'>
      <Head>
        <title>Syncrow</title>
        <meta name='description' content='Generated by create next app' />
        <link
          rel='icon'
          href='https://ik.imagekit.io/jason7531/syncrow/common/Group_1_rkAObjd65.png?ik-sdk-version=javascript-1.4.3&updatedAt=1642343317149'
        />
        <style>
          @import
          url(https://fonts.cdnfonts.com/css/guthen-bloots-personal-use);
        </style>
      </Head>

      <div className='h-screen relative'>
        <Header />
        {/* page 1 */}
        <div className='lg:min-h-[100vh] flex lg:flex-row flex-col justify-center items-center'>
          <div className='relative w-[100%] pt-[10vh] lg:w-[42%] lg:mr-[5%]'>
            <img className='w-[100%] h-[100%] object-cover' src='https://ik.imagekit.io/jason7531/syncrow/IOT/Mask_Group_24_QBfyj44xB.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1642943018991' alt='...' />
            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={{ once: false }}
              transition={{ duration: 0.5 }}
              variants={{
                visible: { opacity: 1, scale: 1 },
                hidden: { opacity: 0, scale: 0 }
              }}
              className='lg:absolute -mt-[20%] lg:-mt-0 mb-[1rem] w-[100%] lg:w-[210%] lg:bottom-[-20%]'>
              <p className='font-[aftika-bold] text-center lg:text-left w-[100%] text-[2rem]  lg:text-[4rem] lg:leading-[2rem]'>Is Your</p>
              <div className='flex lg:flex-row flex-col lg:items-center lg:pl-[10%]'>
                <p style={{ fontFamily: `${guthen}` }} className='text-blue-700 text-[4rem] leading-[4.3rem] text-center lg:text-left lg:text-[7rem] lg:leading-[8rem]'>Industry </p>
                <p className='font-[aftika-bold] text-[2rem] leading-[1.8rem] text-center lg:text-left lg:text-[4rem]'> tomorrow-ready?</p>
              </div>
            </motion.div>
          </div>
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: false }}
            transition={{ duration: 0.5 }}
            variants={{
              visible: { opacity: 1, scale: 1 },
              hidden: { opacity: 0, scale: 0 }
            }}
            className='relative lg:w-[42%] w-[80%] text-center '>
            <p className='lg:w-[80%] py-[1rem]'>Despite having an automated business environment, manufacturing productivity is not utilized at optimal capacity to meet customer demands.</p>
            <p className='lg:w-[80%] py-[1rem]'>The unbalanced workload at stations, production cycle times & quality, or additional operational costs are certain challenges that affect the productivity of businesses.</p>
          </motion.div>
        </div>

        {/* page 2 */}
        <motion.div
          initial="hidden"
          whileInView="visible"
          viewport={{ once: false }}
          transition={{ duration: 0.5 }}
          variants={{
            visible: { opacity: 1, scale: 1 },
            hidden: { opacity: 0, scale: 0 }
          }}
          className='flex items-center flex-col mt-[5rem] px-[10%] lg:px-[25%]'>
          <p className='font-[aftika-bold] mb-[1rem] text-[1.3rem] lg:text-[1.5rem] w-[100%] text-center'>The key challenges faced by industries today are</p>
          <ul className='w-[80%] list-disc'>
            <li className='text-blue-700 text-[1.4rem]'><span className='text-black text-[1rem] pb-[.5rem]'>Smart Asset Monitoring</span></li>
            <li className='text-blue-700 text-[1.4rem]'><span className='text-black text-[1rem] pb-[.5rem]'>Keeping abreast of regulations and managing compliance</span></li>
            <li className='text-blue-700 text-[1.4rem]'><span className='text-black text-[1rem] pb-[.5rem]'>Implementing procedures that allow faster time to market</span></li>
            <li className='text-blue-700 text-[1.4rem]'><span className='text-black text-[1rem] pb-[.5rem]'>Balancing maintenance with throughput</span></li>
            <li className='text-blue-700 text-[1.4rem]'><span className='text-black text-[1rem] pb-[.5rem]'>Ensure customer satisfactions</span></li>
          </ul>
        </motion.div>

        {/* page 3 */}
        <div className='flex flex-col lg:flex-row mt-[3rem] w-[100%] justify-center items-center'>
          <div className='lg:w-[40%]'>
            <img className='w-[100%] h-[100%]' src='https://syncrow.s3.ap-south-1.amazonaws.com/Uploader_blue_r8_GD_7la_TN_70018f7cc3.webp' alt='...' />
          </div>
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: false }}
            transition={{ duration: 0.5 }}
            variants={{
              visible: { opacity: 1, scale: 1 },
              hidden: { opacity: 0, scale: 0 }
            }}
            className='lg:w-[50%] px-[2rem] lg:px-0 text-center lg:text-left lg:pr-[10%]'>
            <p className='mb-[1rem]'>Our solutions help a business to transform its processes in terms of operations, coordination and outcomes.</p>
            <p className='mb-[1rem]'>Syncrow solutions help your implement scalable solutions which leverage the power of</p>
            <ul className='list-disc pl-[25%] lg:pl-[1.5rem] mb-[1rem]'>
              <li className='text-blue-700 text-[1.5rem] text-left leading-[1.4rem]'><span className='text-black text-[1rem]'>Smart Asset Monitoring</span></li>
              <li className='text-blue-700 text-[1.5rem] text-left leading-[1.4rem]'><span className='text-black text-[1rem]'>Smart Connected Workforce</span></li>
              <li className='text-blue-700 text-[1.5rem] text-left leading-[1.4rem]'><span className='text-black text-[1rem]'>Smart Data Driven Automation</span></li>
            </ul>
            <p>Our smart solutions allow you to cut down on the complexities involved in data collection, insight generation and help you make better decisions. When utilized effectively, our smart solutions bring major business benefits and provide you with a competitive advantage.</p>
          </motion.div>
        </div>

        {/* page 4 */}
        <div className='mt-[4rem]'>
          <div className='relative lg:min-h-[100vh]'>
            <div className='relative lg:absolute -z-10 lg:w-[100%] h-[70vh] lg:pl-10  lg:h-[100%] bg-cover bg-[url(https://syncrow.s3.ap-south-1.amazonaws.com/industry_page_4_m_88dc207be1.png)] lg:bg-[url(https://syncrow.s3.ap-south-1.amazonaws.com/businessman_pointing_his_presentation_futuristic_digital_screen_0f03538b45.png)]'>
              {/* <motion.div
                initial="hidden"
                whileInView="visible"
                viewport={{ once: false }}
                transition={{ duration: 0.5 }}
                variants={{
                  visible: { opacity: 1, scale: 1 },
                  hidden: { opacity: 0, scale: 0 }
                }}
                className='absolute mb-[2.5rem] lg:mb-0 w-[100%] flex flex-col justify-center lg:justify-start lg:relative bottom-5 lg:pt-[4rem]'>
                <div className='lg:pl-[18vw] '>
                  <p className='font-[aftika-bold] text-[2rem] leading-[1rem] text-center lg:text-left lg:text-[2.5rem] lg:leading-[1.5rem]'>Benefits of</p>
                </div>
                <div className='flex justify-center lg:justify-start lg:-mt-[.5rem] text-center lg:text-left lg:mb-[.5rem] items-center'>
                  <img className='lg:w-[8vw] lg:mx-[5vw] w-[25%] px-[5%] lg:px-0 h-[100%] object-contain' src="/logo.png" alt="..." />
                  <p className='font-[aftika-bold] text-[4rem] lg:text-[5rem] lg:leading-[1.5rem]'>syncrow</p>
                </div>
                <div className='lg:pl-[18vw]'>
                  <p className='font-[aftika-bold] text-[2rem] leading-[1rem] text-center lg:text-left lg:text-[2.5rem] lg:leading-[1.5rem]'>Industry Automation</p>
                </div>
              </motion.div> */}
              <motion.div
                initial="hidden"
                whileInView="visible"
                viewport={{ once: false }}
                transition={{ duration: 0.5 }}
                variants={{
                  visible: { opacity: 1, scale: 1 },
                  hidden: { opacity: 0, scale: 0 }
                }}
                className=" mb-[2.5rem] lg:mb-0 w-[100%] flex flex-col md:flex-row pt-10 justify-center lg:justify-start lg:relative bottom-5 lg:pt-[4rem]">
                  <div className='flex items-center justify-center'>
                    <img className='w-[20%] h-[40%] md:w-[60%] md:pl-4 lg:px-0 md:h-[60%]' src="/logo.png" alt="..." />
                  </div>
                  <div className='pt-8 md:pt-0'>
                    <p className='font-[aftika-bold] text-[2rem] leading-[1rem] text-center md:text-left lg:text-[2.5rem] lg:leading-[1.5rem]'>Benefits of</p>
                    <p className='font-[aftika-bold] text-[4rem] text-center md:text-left lg:text-[5rem]'>syncrow</p>
                    <p className='font-[aftika-bold] text-[2rem] leading-[2rem] text-center md:text-left lg:text-[2.5rem] lg:leading-[1.5rem]'>Industry Automation</p>
                  </div>
                </motion.div>
              <motion.div
                initial="hidden"
                whileInView="visible"
                viewport={{ once: false }}
                transition={{ duration: 0.5 }}
                variants={{
                  visible: { opacity: 1, scale: 1 },
                  hidden: { opacity: 0, scale: 0 }
                }}
                className='hidden w-[100%] pt-[10%] h-[100%] lg:flex'>
                <div className='w-[30%] mx-[5%]'>
                  <p style={{ fontFamily: `${guthen}` }} className="text-blue-700 text-[2.4rem] leading-[2.2rem] lg:text-[3.5rem] lg:leading-[3.2rem]">Improved</p>
                  <p className='font-[aftika-bold] tracking-wider'>Operational Efficiencies</p>
                  <p className='font-[aftika-extra-light] font-bold pt-[.8rem]'>Smart industrial IoT solutions use real-time data from sensors to monitor and enhance process efficiency, reduce human intervention, and energy costs. All data obtained can be utilized to minimize downtime due to maintenance, unavailability of assets, and lack of human resources in the factory.</p>
                </div>

                <div className='w-[25%]'>
                  <p style={{ fontFamily: `${guthen}` }} className="text-blue-700 text-[2.4rem] leading-[2.2rem] lg:text-[3.5rem] lg:leading-[3.2rem]">Better</p>
                  <p className='font-[aftika-bold] tracking-wider'>Safety & Security</p>
                  <p className='font-[aftika-extra-light] font-bold pt-[.8rem]'>Besides resolving situations faster by coordinating with multiple teams, these solutions allow businesses to improve workplace safety and guard against physical threats using sensors and video cameras that help monitor equipment.</p>
                </div>
              </motion.div>
            </div>
          </div>

          {/* desktop  */}
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: false }}
            transition={{ duration: 0.5 }}
            variants={{
              visible: { opacity: 1, scale: 1 },
              hidden: { opacity: 0, scale: 0 }
            }}
            className='hidden lg:flex py-[5rem]'>
            <div className='w-[30%] mx-[5%]'>
              <p style={{ fontFamily: `${guthen}` }} className="text-blue-700 text-[2.4rem] leading-[2.2rem] lg:text-[3.5rem] lg:leading-[3.2rem]">Faster</p>
              <p className='font-[aftika-bold] tracking-wider'>Decision Making</p>
              <p className='font-[aftika-extra-light] font-bold pt-[.8rem]'>Organizations can use real-time operational insights to make faster and smarter business decisions and reduce operating costs. These IoT-enabled solutions help distribute intelligence and prioritize all business decisions.</p>
            </div>

            <div className='w-[50%]'>
              <p style={{ fontFamily: `${guthen}` }} className="text-blue-700 text-[2.4rem] leading-[2.2rem] lg:text-[3.5rem] lg:leading-[3.2rem]">A New Level</p>
              <p className='font-[aftika-bold] tracking-wider'>of Business Intelligence</p>
              <p className='font-[aftika-extra-light] font-bold pt-[.8rem]'>Smart solutions can serve as a forecasting tool for better decision-making by constantly monitoring, aggregating, and analyzing data from various sensors installed across the factory or deployed to the entire staff. These sensors help supervisors to collect real-time data which in turn allows companies to obtain insights into various operations and initiate preventative actions.
                <br /><br />
                To be in the league of growing businesses, getting smart can be an optimal solution for your business. By incorporating smart industrial solutions in a business, enterprises can convert real-time data into actionable insights which in turn can help in better decision-making.</p>
            </div>
          </motion.div>
          {/* mobile  */}
          <div className='block lg:hidden py-[2rem]'>
            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={{ once: false }}
              transition={{ duration: 0.5 }}
              variants={{
                visible: { opacity: 1, scale: 1 },
                hidden: { opacity: 0, scale: 0 }
              }}
              className='flex justify-center'>
              <div className='w-[50%]'>
                <p style={{ fontFamily: `${guthen}` }} className="text-blue-700 text-[2.4rem] leading-[2.2rem] lg:text-[3.5rem] lg:leading-[3.2rem]">Improved</p>
                <p className='font-[aftika-bold] text-[.8rem] tracking-wider'>Operational Efficiencies</p>
                <p className='font-[aftika-extra-light] text-[.8rem] font-bold pt-[.8rem]'>Smart industrial IoT solutions use real-time data from sensors to monitor and enhance process efficiency, reduce human intervention, and energy costs. All data obtained can be utilized to minimize downtime due to maintenance, unavailability of assets, and lack of human resources in the factory.</p>
              </div>
            </motion.div>
            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={{ once: false }}
              transition={{ duration: 0.5 }}
              variants={{
                visible: { opacity: 1, scale: 1 },
                hidden: { opacity: 0, scale: 0 }
              }}
              className='flex justify-evenly py-[3rem]'>
              <div className='w-[40%]'>
                <div className='w-[100%]'>
                  <p style={{ fontFamily: `${guthen}` }} className="text-blue-700 text-[2.4rem] leading-[2.2rem] lg:text-[3.5rem] lg:leading-[3.2rem]">A New Level</p>
                  <p className='font-[aftika-bold] text-[.8rem] tracking-wider'>of Business Intelligence</p>
                  <p className='font-[aftika-extra-light] text-[.8rem] font-bold pt-[.8rem]'>Smart solutions can serve as a forecasting tool for better decision-making by constantly monitoring, aggregating, and analyzing data from various sensors installed across the factory or deployed to the entire staff. These sensors help supervisors to collect real-time data which in turn allows companies to obtain insights into various operations and initiate preventative actions.
                    <br /><br />
                    To be in the league of growing businesses, getting smart can be an optimal solution for your business. By incorporating smart industrial solutions in a business, enterprises can convert real-time data into actionable insights which in turn can help in better decision-making.</p>
                </div>
              </div>
              <div className='w-[40%]'>

                <div className='w-[100%]'>
                  <p style={{ fontFamily: `${guthen}` }} className="text-blue-700 text-[2.4rem] leading-[2.2rem] lg:text-[3.5rem] lg:leading-[3.2rem]">Better</p>
                  <p className='font-[aftika-bold] text-[.8rem] tracking-wider'>Safety & Security</p>
                  <p className='font-[aftika-extra-light] text-[.8rem] font-bold pt-[.8rem]'>Besides resolving situations faster by coordinating with multiple teams, these solutions allow businesses to improve workplace safety and guard against physical threats using sensors and video cameras that help monitor equipment.</p>
                </div>
                <div className='w-[100%] mt-[40%] mx-[5%]'>
                  <p style={{ fontFamily: `${guthen}` }} className="text-blue-700 text-[2.4rem] leading-[2.2rem] lg:text-[3.5rem] lg:leading-[3.2rem]">Faster</p>
                  <p className='font-[aftika-bold] text-[.8rem] tracking-wider'>Decision Making</p>
                  <p className='font-[aftika-extra-light] text-[.8rem] font-bold pt-[.8rem]'>Organizations can use real-time operational insights to make faster and smarter business decisions and reduce operating costs. These IoT-enabled solutions help distribute intelligence and prioritize all business decisions.</p>
                </div>

              </div>

            </motion.div>
          </div>

        </div>
        <Footer />
      </div>
    </div >
  );
}
