import Header from '../../components/header';
import Footer from '../../components/footer';
import Head from 'next/head';
import { motion } from 'framer-motion';

export default function City() {
  const guthen = 'Guthen Bloots Personal Use';
  return (
    <div>
      <Head>
        <title>Syncrow</title>
        <meta name='description' content='Generated by create next app' />
        <link
          rel='icon'
          href='https://ik.imagekit.io/jason7531/syncrow/common/Group_1_rkAObjd65.png?ik-sdk-version=javascript-1.4.3&updatedAt=1642343317149'
        />
        <style>
          @import
          url(https://fonts.cdnfonts.com/css/guthen-bloots-personal-use);
        </style>
      </Head>
      <Header color={"white"} />
      {/* page 1 */}
      <div className='relative lg:h-[100vh] h-[100%] flex lg:flex-row flex-col items-center justify-center lg:justify-end lg:text-white'>
        <div className='relative lg:absolute lg:py-[10vh] -z-10 bg-cover lg:top-0 lg:min-h-[100%] lg:w-[100%] bg-bottom h-[45vh] mt-[10vh] lg:mt-0 w-[100%]  lg:left-0 bg-[url(https://syncrow.s3.ap-south-1.amazonaws.com/smart_cities_page_1_m_614536183b.png)] lg:bg-[url(https://syncrow.s3.ap-south-1.amazonaws.com/Mask_Group_51_7adfb584d1.png)]'></div>
        <div className='lg:w-[60%] py-[4rem] lg:py-0 flex flex-col justify-center items-center h-[100%]'>
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: false }}
            transition={{ duration: 0.5 }}
            variants={{
              visible: { opacity: 1, scale: 1 },
              hidden: { opacity: 0, scale: 0 }
            }}
            className='w-[100%] text-center'>
            <p className='lg:text-[3rem] text-[2.7rem] leading-[2.5rem] lg:leading-[2.8rem] font-[aftika-semibold] lg:font-[aftika-bold]'>The Time</p>
            <p className='lg:text-[3rem] text-[2.7rem] leading-[2.5rem] font-[aftika-semibold] lg:leading-[2.8rem] lg:font-[aftika-bold]'>For</p>
            <p style={{ fontFamily: `${guthen}` }} className="text-blue-700 lg:text-[9rem] text-[7rem] leading-[3.5rem] lg:leading-[4.5rem]">Smart</p>
            <p className='lg:text-[4.5rem] mt-[1.5rem] text-[3rem] leading-[2.5rem] font-[aftika-semibold] lg:leading-[3.8rem] lg:font-[aftika-bold]'>City is Now</p>
          </motion.div>
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: false }}
            transition={{ duration: 0.5 }}
            variants={{
              visible: { opacity: 1, scale: 1 },
              hidden: { opacity: 0, scale: 0 }
            }}
            className='w-[100%] flex justify-center items-center px-[10%] text-center lg:text-left lg:px-0 lg:pl-[10%] mt-[2rem]'>
            <p className='lg:w-[50%] font-[aftika-extra-light] text-[.8rem]'>Our smart city solutions don’t just provide cost-effective and efficient municipal services, enhanced public transportation and infrastructure, optimized use of resources as well as faster responsiveness and improved decision-making but also new revenue opportunities for you unlocked by analytics that also means cleaner cities, better environments and improved quality of life.</p>
          </motion.div>
        </div>
      </div>
      {/* page 2 */}
      <div className='flex justify-evenly flex-wrap lg:flex-nowrap lg:px-[5%] py-[3rem] lg:py-0 lg:my-[3rem]'>
        <motion.div
          initial="hidden"
          whileInView="visible"
          viewport={{ once: false }}
          transition={{ duration: 0.5 }}
          variants={{
            visible: { opacity: 1, scale: 1 },
            hidden: { opacity: 0, scale: 0 }
          }}
          className='my-[1rem] lg:my-0 px-[2%] w-[45%] lg:w-auto'>
          <p style={{ fontFamily: `${guthen}` }} className="text-blue-700 text-[2.4rem] leading-[2.2rem] lg:text-[3.5rem] lg:leading-[3.2rem]">Easy</p>
          <p className='font-[aftika-bold] tracking-wider'>Implementation</p>
          <p className='font-[aftika-extra-light] font-bold pt-[.8rem]'>Our smart city solutions are powered by a modern networking infrastructure platform that works with the existing system with minimum disruption.</p>
        </motion.div>
        <motion.div
          initial="hidden"
          whileInView="visible"
          viewport={{ once: false }}
          transition={{ duration: 0.5 }}
          variants={{
            visible: { opacity: 1, scale: 1 },
            hidden: { opacity: 0, scale: 0 }
          }}
          className='my-[1rem] lg:my-0 px-[2%] w-[45%]  lg:w-auto'>
          <p style={{ fontFamily: `${guthen}` }} className="text-blue-700 text-[2.4rem] leading-[2.2rem] lg:text-[3.5rem] lg:leading-[3.2rem]">Comprehensive</p>
          <p className='font-[aftika-bold] tracking-wider'>Security</p>
          <p className='font-[aftika-extra-light] font-bold pt-[.8rem]'>We follow best practices to keep all data secure by following industrial standards in compliance with various industry and federal regulations.</p>
        </motion.div>
        <motion.div
          initial="hidden"
          whileInView="visible"
          viewport={{ once: false }}
          transition={{ duration: 0.5 }}
          variants={{
            visible: { opacity: 1, scale: 1 },
            hidden: { opacity: 0, scale: 0 }
          }}
          className='my-[1rem] lg:my-0 px-[2%]  w-[45%] lg:w-auto'>
          <p style={{ fontFamily: `${guthen}` }} className="text-blue-700 text-[2.4rem] leading-[2.2rem] lg:text-[3.5rem] lg:leading-[3.2rem]">Accelerate</p>
          <p className='font-[aftika-bold] tracking-wider'>ROI</p>
          <p className='font-[aftika-extra-light] font-bold pt-[.8rem]'>Our solutions are equipped with the latest technologies like advanced analytics, deep learning and AI that provide real-time visibility and simplify solution deployments that deliver higher ROI.</p>
        </motion.div>
        <motion.div
          initial="hidden"
          whileInView="visible"
          viewport={{ once: false }}
          transition={{ duration: 0.5 }}
          variants={{
            visible: { opacity: 1, scale: 1 },
            hidden: { opacity: 0, scale: 0 }
          }}
          className='my-[1rem] lg:my-0 px-[2%]  w-[45%] lg:w-auto'>
          <p style={{ fontFamily: `${guthen}` }} className="text-blue-700 text-[2.4rem] leading-[2.2rem] lg:text-[3.5rem] lg:leading-[3.2rem]">Proven</p>
          <p className='font-[aftika-bold] tracking-wider'>Stability</p>
          <p className='font-[aftika-extra-light] font-bold pt-[.8rem]'>The platform we use supports an increasing number of application features, connected devices, users, and analytics capabilities so that it can meet future needs.</p>
        </motion.div>



      </div>
      <Footer />
    </div>
  );
}
