import { motion } from 'framer-motion';
import Head from 'next/head';
import Footer from '../components/footer';
import Header from '../components/header';
const About = () => {

  const guthen = 'Guthen Bloots Personal Use';


  return (
    <>
      <Head>
        <title>Syncrow</title>
        <meta name='description' content='Generated by create next app' />
        <link
          rel='icon'
          href='https://ik.imagekit.io/jason7531/syncrow/common/Group_1_rkAObjd65.png?ik-sdk-version=javascript-1.4.3&updatedAt=1642343317149'
        />

        {/* guthen font  */}
        <link href="https://fonts.cdnfonts.com/css/guthen-bloots-personal-use"  rel="stylesheet" />


        {/* poppins font  */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet" />
        {/* fontawesome */}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossOrigin="anonymous" referrerpolicy="no-referrer" />

      </Head>
      <Header color='white' />
      {/* page 1 */}

      <div className=' flex flex-col pt-10 md:pt-0 lg:flex-row justify-center lg:justify-evenly bg-[#00000050] text-white lg:items-center min-h-[100vh] relative'>
        <img className='absolute w-full h-full -z-10 object-cover' src='https://syncrow.s3.ap-south-1.amazonaws.com/about1_Fwj_C_u43s_a1729382b9.webp' alt='' />
        <motion.div
          initial="hidden"
          whileInView="visible"
          viewport={{ once: false }}
          transition={{ duration: 0.3 }}
          variants={{
            visible: { opacity: 1, scale: 1 },
            hidden: { opacity: 0, scale: 0 }
          }}
          className='lg:w-[30%]'>
          <h3 style={{ fontFamily: `${guthen}` }} className="lg:text-[9rem] text-center lg:text-left lg:leading-[8rem] text-[4rem] leading-[3.8rem] pt-[5rem] lg:pt-0">Driven</h3>
          <p className='lg:text-[4rem] lg:leading-[3.5rem] lg:pl-[3rem] lg:-mt-[1rem] text-center text-[1.5rem]  lg:text-left px-[2rem] lg:px-0'>by creative Innovation</p>
        </motion.div>
        <div className='lg:w-[30%] mt-[2rem] lg:mt-0'>
          <motion.p
            initial="hidden"
            whileInView="visible"
            viewport={{ once: false }}
            transition={{ duration: 0.3 }}
            variants={{
              visible: { opacity: 1, scale: 1 },
              hidden: { opacity: 0, scale: 0 }
            }}
            className=' font-thin lg:font-medium py-[.5rem] lg:py-0 text-center lg:text-left px-[2rem] lg:px-0'>Syncrow is the refined outcome built on the synergy of aesthetics and cutting-edge technology. We have paved a path for merging creativity with technology and are delivering state-of-the-art automation solutions.</motion.p>
            <br/>
          <motion.p
            initial="hidden"
            whileInView="visible"
            viewport={{ once: false }}
            transition={{ duration: 0.3 }}
            variants={{
              visible: { opacity: 1, scale: 1 },
              hidden: { opacity: 0, scale: 0 }
            }}
            className=' font-thin lg:font-medium py-[.5rem] lg:py-0 text-center lg:text-left px-[2rem] lg:px-0'>Our aim is to transform and improve the way people enjoy their everyday life. Making their daily tasks easier and adding more to their quality of life.</motion.p>
            <br/>
          <motion.p
            initial="hidden"
            whileInView="visible"
            viewport={{ once: false }}
            transition={{ duration: 0.3 }}
            variants={{
              visible: { opacity: 1, scale: 1 },
              hidden: { opacity: 0, scale: 0 }
            }}
            className=' font-thin lg:font-medium py-[.5rem] lg:py-0 text-center lg:text-left px-[2rem] lg:px-0'>This lies at the root of how all of our solutions are shaped. By utilizing the latest tech innovations, we’ve created faster, better, and more convenient solutions that address the needs of global customers.</motion.p>
        </div>
      </div>

      {/* page 2 */}
      <div className='text-white bg-blue-700 py-[5vh] px-[9vw] lg:py-[10vh] lg:px-[10vw]'>
        <motion.p
          initial="hidden"
          whileInView="visible"
          viewport={{ once: false }}
          transition={{ duration: 0.3 }}
          variants={{
            visible: { opacity: 1, scale: 1 },
            hidden: { opacity: 0, scale: 0 }
          }}
          className='text-left lg:text-[3rem] text-[2rem]  font-medium lg:leading-[3rem] '>Our promise is to deliver scalable, customizable, and affordable solutions for an upgraded lifestyle or industry experience.</motion.p>

      </div>

      {/* page 3 */}
      <div className='relative bg-[#000] lg:bg-[#00000000] z-0 text-white lg:min-h-[120vh] min-h-[100vh] flex flex-col lg:flex-row lg:justify-center'>
        {/* desktop img  */}
        <img className='absolute hidden lg:block lg:w-full lg:h-full lg:top-0 lg:left-0 -z-40' src='https://ik.imagekit.io/jason7531/syncrow/About/roboArm_lpkwpTfmu.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1642780739863' alt='' />
        {/* mobile image  */}
        <img className='absolute block lg:hidden min-h-[30vh] lg:w-full lg:h-full lg:top-0 lg:left-0 -z-10' src='https://ik.imagekit.io/jason7531/syncrow/About/roboArm_lpkwpTfmu.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1642780739863' alt='' />
        <div className='lg:w-[20vw] flex flex-col justify-center'>
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: false }}
            transition={{ duration: 0.3 }}
            variants={{
              visible: { opacity: 1, scale: 1 },
              hidden: { opacity: 0, scale: 0 }
            }}
            className='pt-[5vh] lg:py-0 h-[30vh] lg:h-auto'>
            <p className='lg:text-[3rem] text-[1.5rem] font-medium  text-center lg:text-left'>See What</p>
            <h3 style={{ fontFamily: `${guthen}` }} className="lg:text-[6rem] text-center lg:text-left lg:leading-[5rem] text-[3.5rem] leading-[3.2rem]">Drives Us</h3>
          </motion.div>
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: false }}
            transition={{ duration: 0.3 }}
            variants={{
              visible: { opacity: 1, scale: 1 },
              hidden: { opacity: 0, scale: 0 }
            }}
            className='text-center lg:text-left p-[2rem] lg:p-0'>
            <p className='lg:pt-[2rem]'>As an organization, we believe in pioneering the IoT to deliver boutique solutions that are tailored to your needs, personal or industry. </p>
            <p className='pt-[1rem] lg:pt-0'>Within our core values, we stay strong to delivering solutions which are:</p>
          </motion.div>

        </div>
        <div className='lg:w-[60vw] lg:py-[4rem] py-[3rem] flex lg:h-[85vh] flex-wrap justify-center items-start'>
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: false }}
            transition={{ duration: 0.3 }}
            variants={{
              visible: { opacity: 1, scale: 1 },
              hidden: { opacity: 0, scale: 0 }
            }}
            className='lg:w-[29vw] w-[45%] lg:px-[2rem] px-[.5rem] py-[.5rem] lg:py-0'>
            <p className='font-medium  mb-[.5rem] text-[1rem]  lg:text-[2rem]'>Scalable</p>
            <p className='text-[.7rem] lg:text-[.8rem]'>Our solutions are evolution-oriented. By tapping into the most recent IoT technologies, we ensure that our solutions are creatively shaped to comply with the coming changes and are not a stop-gap solution to your needs.</p>
          </motion.div>
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: false }}
            transition={{ duration: 0.3 }}
            variants={{
              visible: { opacity: 1, scale: 1 },
              hidden: { opacity: 0, scale: 0 }
            }}
            className='lg:w-[29vw] w-[45%] lg:px-[2rem] px-[.5rem] py-[.5rem] lg:py-0'>
            <p className='font-medium  mb-[.5rem] text-[1rem]  lg:text-[2rem]'>Affordable</p>
            <p className='text-[.7rem] lg:text-[.8rem]'>Our energies are directed towards making a variety of next-gen technology available today. While doing so, we also keep a firm eye on making it affordable. As an organization, we firmly believe that technology should work for our customers which allows them to live life without compromising on luxury.</p>
          </motion.div>
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: false }}
            transition={{ duration: 0.3 }}
            variants={{
              visible: { opacity: 1, scale: 1 },
              hidden: { opacity: 0, scale: 0 }
            }}
            className='lg:w-[29vw] w-[45%] lg:px-[2rem] px-[.5rem] py-[.5rem] lg:py-0'>
            <p className='font-medium  mb-[.5rem] text-[1rem]  lg:text-[2rem]'>Innovative</p>
            <p className='text-[.7rem] lg:text-[.8rem]'>Innovation is in our blood. It is the energy that drives us to hit the mark with every new solution we craft. After every success, our thirst for innovation leads us back to the drawing table to create technologies that upgrade lifestyle and fit a variety of different industries.</p>
          </motion.div>
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: false }}
            transition={{ duration: 0.3 }}
            variants={{
              visible: { opacity: 1, scale: 1 },
              hidden: { opacity: 0, scale: 0 }
            }}
            className='lg:w-[29vw] w-[45%] lg:px-[2rem] px-[.5rem] py-[.5rem] lg:py-0'>
            <p className='font-medium  mb-[.5rem] text-[1rem]  lg:text-[2rem]'>Professionalism</p>
            <p className='text-[.7rem] lg:text-[.8rem]'>As a family, the passion and ambition to put our best foot forward, every time, is ingrained in us. We aim to provide all our customers with a happy and uniform experience while also providing the best solution for their needs. This is why we are one of the leaders in the IoT and Automation solutions industry.</p>
          </motion.div>
        </div>

      </div>

      {/* page 4 */}
      <div id="syncrowMember" className='flex lg:flex-row flex-col-reverse justify-center lg:h-[72vh] items-center lg:items-end'>
        <motion.div
          initial="hidden"
          whileInView="visible"
          viewport={{ once: false }}
          transition={{ duration: 0.3 }}
          variants={{
            visible: { opacity: 1, scale: 1 },
            hidden: { opacity: 0, scale: 0 }
          }}
          className='lg:w-[40%] lg:flex lg:justify-center lg:items-center'>
          <img className='object-cover h-[65vh]' src='/Girl.png' alt='' />
        </motion.div>
        <div className='lg:w-[40%] mt-[5rem] mb-[3rem] lg:mb-0 px-[2rem] lg:pb-[10vh] lg:px-0 lg:mt-0'>
          <motion.h3
          initial="hidden"
          whileInView="visible"
          viewport={{ once: false }}
          transition={{ duration: 0.3 }}
          variants={{
            visible: { opacity: 1, scale: 1 },
            hidden: { opacity: 0, scale: 0 }
          }}
          style={{ fontFamily: `${guthen}` }} className="font-medium lg:text-[6rem] text-center lg:text-left lg:leading-[5rem] text-[3rem] leading-[2.8rem] text-blue-700">Become a part of</motion.h3>
          <motion.p
          initial="hidden"
          whileInView="visible"
          viewport={{ once: false }}
          transition={{ duration: 0.3 }}
          variants={{
            visible: { opacity: 1, scale: 1 },
            hidden: { opacity: 0, scale: 0 }
          }}
          className='lg:text-[2rem] lg:leading-[1.8rem] text-[2rem] text-center lg:text-left font-bold text-black'>Syncrow</motion.p>
          <motion.p
          initial="hidden"
          whileInView="visible"
          viewport={{ once: false }}
          transition={{ duration: 0.3 }}
          variants={{
            visible: { opacity: 1, scale: 1 },
            hidden: { opacity: 0, scale: 0 }
          }}
          className='lg:w-[60%] text-[#000] text-center lg:text-left mt-[1rem] lg:mt-0 py-[1rem]'>Interested in joining the Syncrow Family? Passionate about designing the future of smart technology?</motion.p>
          <motion.p
          initial="hidden"
          whileInView="visible"
          viewport={{ once: false }}
          transition={{ duration: 0.3 }}
          variants={{
            visible: { opacity: 1, scale: 1 },
            hidden: { opacity: 0, scale: 0 }
          }}
          className='lg:w-[60%] text-[#000] text-center lg:text-left py-[1rem]'>Apply for open positions. Send in your CV to careers@syncrow.ae</motion.p>
        </div>
      </div>

      <Footer />

    </>
  )
}

export default About;