import Head from 'next/head';
import Footer from '../components/footer';
import Header from '../components/header';
import buildingAnimation from './lotties/building.json';
import phoneAnimation from './lotties/phone.json';
import waterAnimation from './lotties/water.json';
import exclamationAnimation from './lotties/exclamation.json'
import contactExpertAnimation from "./lotties/ask-your-expert.json";
import energyAnimation from "./lotties/energy-saving.json"
import coldAnimation from "./lotties/cold-temperature.json"

import Lottie from 'react-lottie';
import { motion } from 'framer-motion';

const Apartment = () => {
    const guthen = 'Guthen Bloots Personal Use';


    const buildingOptions = {
        loop: true,
        autoplay: true,
        animationData: buildingAnimation,
        rendererSettings: {
            preserveAspectRatio: 'xMidYMid slice',
        },
    };

    const phoneOptions = {
        loop: true,
        autoplay: true,
        animationData: phoneAnimation,
        rendererSettings: {
            preserveAspectRatio: 'xMidYMid slice',
        },
    };

    const waterOptions = {
        loop: true,
        autoplay: true,
        animationData: waterAnimation,
        rendererSettings: {
            preserveAspectRatio: 'xMidYMid slice',
        },
    };

    const exclamationOptions = {
        loop: true,
        autoplay: true,
        animationData: exclamationAnimation,
        rendererSettings: {
            preserveAspectRatio: 'xMidYMid slice',
        },
    };
    const contactExpertOptions = {
        loop: true,
        autoplay: true,
        animationData: contactExpertAnimation,
        renderedSettings: {
            // preserveAspectRatio:'xMidYMid slice'
        },
    };
    const coldOptions = {
        loop: true,
        autoplay: true,
        animationData: coldAnimation,
        renderedSettings: {
            preserveAspectRatio:'xMidYMid slice'
        },
    };
    const energyOptions = {
        loop: true,
        autoplay: true,
        animationData: energyAnimation,
        rendererSettings: {
          preserveAspectRatio: 'xMidYMid slice',
        },
      };
    return (
        <>
            <Head>
                <title>Syncrow</title>
                <meta name='description' content='Generated by create next app' />
                <link
                    rel='icon'
                    href='https://ik.imagekit.io/jason7531/syncrow/common/Group_1_rkAObjd65.png?ik-sdk-version=javascript-1.4.3&updatedAt=1642343317149'
                />

                {/* guthen font  */}
                <link href="https://fonts.cdnfonts.com/css/guthen-bloots-personal-use" rel="stylesheet" />


                {/* poppins font  */}
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
                <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet" />
                {/* fontawesome */}
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossOrigin="anonymous" referrerpolicy="no-referrer" />

            </Head>
            <Header color='white' />

            {/* page 1 */}

            <div className="relative w-[100%] h-[100vh] overflow-hidden">
                <img className="absolute top-0 left-0 w-full h-full -z-10 object-cover" src="https://syncrow.s3.ap-south-1.amazonaws.com/Mask_Group_49_4ad2356190.png" alt="..." />
                <motion.p
                    initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.5 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}
                    style={{ fontFamily: `${guthen}` }} className="absolute text-[3.5rem]  lg:text-[4rem] font-medium text-center top-[40%] lg:w-[40%] lg:top-[20%] text-white lg:right-[5%]">Building the future of your connected residences</motion.p>
            </div>

            {/* page 2 */}
            <div className="relative w-[100%] lg:min-h-[100vh] flex flex-col lg:flex-row lg:justify-end overflow-hidden lg:pr-[5%]">
                {/* desktop img  */}
                <img className="hidden lg:block lg:absolute lg:top-0 lg:left-0 h-[51vh] object-left lg:w-full lg:h-full -z-10 object-cover" src="https://syncrow.s3.ap-south-1.amazonaws.com/Mask_Group_36_d5c6bd5863.png" alt="..." />
                {/* mobile img  */}
                <img className="lg:hidden block lg:absolute lg:top-0 lg:left-0 h-[51vh] object-left lg:w-full lg:h-full -z-10 object-cover" src="/apartments-page-2-m.png" alt="..." />
                <div className='bg-[#000] lg:w-[45%] flex flex-col p-[2rem] lg:p-0 justify-center text-white lg:items-start items-center lg:bg-[#00000000]'>
                    <motion.h3
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className='text-[2rem] leading-[1.8rem]'>The future of </motion.h3>
                    <motion.h3
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        style={{ fontFamily: `${guthen}` }}
                        className="text-[4rem] lg:mb-[3rem] text-center lg:text-left text-white lg:pr-[10%]">Living Is Wireless</motion.h3>
                    <motion.p
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className='py-[.5rem] lg:font-[aftika-extra-light] font-extralight lg:text-left text-center'>Apartment automation is connecting all the functional elements (Lights, HVAC, CCTV, etc) of a residential building to a central hub via a network.</motion.p>
                    <motion.p
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className='py-[.5rem] lg:text-left text-center'>This allows for proactive and contextual actions. Eg: Automatically triggering alarms, sensing intruders, recording and notifying security, etc.</motion.p>
                    <motion.p
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className='py-[.5rem] lg:text-left text-center'>Syncrow Apartment Automation is focused on configuring and maintaining the optimal utilization of apartment resources while keeping them in sync for the preferred usage. The core function is to lay down the technology and hardware in the best possible way to create a residential space that is safe, secure, and intelligent.</motion.p>
                    <motion.p
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className='py-[.5rem] lg:text-left text-center'>Syncrow achieves this through their retro-fit installations allowing any building to become an intelligent apartment. No need to change existing wiring or remodel the building in any manner.</motion.p>
                    <motion.p
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className='py-[.5rem] lg:text-left text-center'>Syncrow achieves this through their retro-fit installations allowing any building to become an intelligent apartment. No need to change existing wiring or remodel the building in any manner.</motion.p>
                </div>
            </div>
            {/* page 3 */}
            <div className="relative w-[100%] lg:min-h-[100vh] flex flex-col lg:flex-row  overflow-hidden lg:pr-[5%]">
                {/* desktop img  */}
                <img className="lg:absolute lg:top-0 lg:left-0 h-[41vh] object-right-top lg:w-full lg:h-full -z-10 object-cover" src="https://syncrow.s3.ap-south-1.amazonaws.com/5g_communication_technology_internet_network_8c7cb4644c.png" alt="..." />

                <div className='lg:text-white lg:w-[40%] lg:pl-[5%] flex flex-col lg:p-[2rem]  justify-center lg:items-start items-center'>
                    <motion.h3
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        style={{ fontFamily: `${guthen}` }} className="text-[4rem] leading-[4rem] lg:mb-[1rem] p-[2rem] lg:p-0 text-center lg:text-left lg:pr-[10%]">Get a Feel of How</motion.h3>
                    <motion.div
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className='flex lg:px-0 px-[2rem] items-center'>
                        <img className='object-contain w-[20%] lg:w-auto lg:h-[6rem] pt-[1rem] lg:mr-[2rem] mr-[5%]' src='/logo.png' alt='' />
                        <h3 className='text-[3rem] md:text-[4rem] font-bold'>syncrow</h3>
                    </motion.div>
                    <motion.p
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className='lg:text-[2rem] leading-[2rem] lg:font-bold text-center lg:px-0 px-[2rem] lg:text-left '>upgrades your home to a smarter living experience</motion.p>

                    <motion.div
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className="mt-[2.5rem] lg:px-0 px-[2rem] pb-[2rem] lg:pb-0">
                        <div className="flex mt-[1rem]">
                            <div className="mr-[1rem] flex justify-center items-center">
                                
 <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                            </div>
                            <p className="font-normal mt-2">Ask our expert</p>
                        </div>
                        <div className="flex mt-[1rem]">
                            <div className="mr-[1rem] flex justify-center items-center">
                                
 <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                            </div>
                            <p className="font-normal mt-2">Choose your bundle Or Design your own.</p>
                        </div>
                    </motion.div>
                </div>
            </div>


            {/* page 4 */}
            <div className='bg-blue-700 w-[100%] text-white lg:min-h-[70vh] p-[2rem] flex flex-col lg:flex-row'>
                <div className='lg:w-[50%] flex flex-col justify-center items-center'>
                    <motion.div
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className='lg:w-[50%]'>
                        <Lottie
                            options={buildingOptions}
                            width={'100%'}
                        // height={'40%'}
                        />
                    </motion.div>
                    <motion.h3
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        style={{ fontFamily: `${guthen}` }} className="text-[4rem] text-center leading-[4rem] mt-[3rem]">Not just a Building</motion.h3>
                    <motion.p
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className='lg:text-[1.7rem] lg:font-bold text-[2rem]'>but a lifestyle</motion.p>
                </div>
                <div className='lg:w-[50%] flex flex-col justify-center lg:items-start items-center lg:pr-[10%]'>
                    <motion.p
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className='lg:text-left lg:font-[aftika-extra-light] lg:font-extralight text-center py-[.7rem]'>Elevate the collective lifestyle of residents while becoming more energy-efficient and reducing operational costs.</motion.p>
                    <motion.p
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className='lg:text-left lg:font-[aftika-extra-light] lg:font-extralight text-center py-[.7rem]'>Syncrow Intelligent Apartment Automation allows you to create an infrastructure of convenience, safety, and efficiency.</motion.p>
                    <motion.p
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className='lg:text-left lg:font-[aftika-extra-light] lg:font-extralight text-center py-[.7rem]'>Think about how much energy can be saved with smart lobby lights, or the disaster that can be averted with instant alerts during emergencies.</motion.p>
                    <motion.p
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className='lg:text-left lg:font-[aftika-extra-light] lg:font-extralight text-center py-[.7rem]'>While a smart system keeps giving back over years, the adoption of this technology is quite easy.</motion.p>
                    <motion.p
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className='lg:text-left lg:font-[aftika-extra-light] lg:font-extralight text-center py-[.7rem]'>With Syncrow Smart Systems, it’s just a simple 3-step process that allows you to convert your apartment into a future-ready living experience.</motion.p>
                </div>

            </div>

            {/* page 5 */}
            <div className='flex flex-col pt-[4rem]'>

                <div className='flex flex-col lg:flex-row lg:justify-evenly lg:px-[10%]'>
                    <motion.div
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className='lg:w-[40%] flex flex-col mx-[2rem] lg:p-0 lg:items-start'>
                        <h3 style={{ fontFamily: `${guthen}` }} className="text-[4rem] text-center leading-[4rem] lg:mt-[3rem] text-blue-700">Leap-fold towards a </h3>
                        <p className='text-center lg:text-left font-bold text-[2rem] leading-[2.5rem]'>greener, safer, convenient and state-of-the-art lifestyle experience.</p>
                    </motion.div>
                    <motion.div
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className='lg:w-[40%] flex items-end'>
                        <div className="mt-[2.5rem] lg:px-0 px-[2rem] pb-[2rem] lg:pb-0">
                            <div className="flex mt-[1rem]">
                                <div className="mr-[1rem] flex justify-center items-center">
                                    
 <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                                </div>
                                <p className="font-normal mt-2">Ask our expert</p>
                            </div>
                            <div className="flex mt-[1rem]">
                                <div className="mr-[1rem] flex justify-center items-center">
                                    
 <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                                </div>
                                <p className="font-normal mt-2">Choose your bundle Or Design your own.</p>
                            </div>
                        </div>
                    </motion.div>
                </div>
                {/* <img className='object-contain' src="https://syncrow.s3.ap-south-1.amazonaws.com/Mask_Group_37_a5cd8019a0.png" alt="" /> */}
                <img className='object-contain' src="/apartments-page-5.png" alt="" />
            </div>

            {/* page 6 */}
            <div className='relative min-h-[80vh] flex lg:justify-end'>
                {/* desktop image  */}
                <img className='hidden lg:block absolute h-full w-full -z-10 object-cover ' src="https://syncrow.s3.ap-south-1.amazonaws.com/Mask_Group_38_11a1b0b760.png" alt="" />
                {/* mobile img  */}
                <img className=' block lg:hidden absolute h-full w-full -z-10 object-cover ' src="/apartments-page-6-m.png" alt="" />
                <motion.div
                    initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.5 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}
                    className='lg:w-[40%] lg:pr-[10%] pt-[2rem] lg:px-0  px-[2rem] lg:pt-[10%]'>
                    <p className='lg:text-left text-sm md:text-md text-center py-[.5rem]'>A home isn’t just set in the bricks and mortars, but the experience offered by the residents.</p>
                    <p className='lg:text-left text-sm md:text-md text-center py-[.5rem]'>Syncrow Smart Automation Systems deliver just that. An experience designed from the ground up, customized to suit your needs and expectations, set to deliver a connected, future-ready, luxurious lifestyle.</p>
                </motion.div>

            </div>
            <div className="tablet:mx-20 mx-8 items-center middle:flex hidden">
            <div className="flex-1 middle:pl-20">
                <motion.h1  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}  ><span className='text-7xl desktop:text-8xl text-default font-thin'
            style={{ fontFamily: `${guthen}` }}>Energy</span></motion.h1>
                <motion.h1  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className='font-semibold tracking-wide -mt-10 text-4xl'>Efficiency</motion.h1>
                <motion.p  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className="mt-6  font-[aftika-light] tracking-wide leading-7 text-base middle:text-left text-center">Smart Home Automation allows everyone to contribute towards a better environment. Our intelligent sensors allow you to save energy whenever you are not at home. And if that’s not enough, you also gain insights into your energy consumption and can personalize schedules accordingly.
                <br /><br />
                Take a step towards a greener lifestyle with intelligent automation.</motion.p>
            </div>
            <div className="flex-initial w-5/12">
            <Lottie options={energyOptions} />
            </div>
        </div>

        <div className="middle:hidden flex flex-col items-center justify-center mt-10 tablet:mx-20 mx-8 pb-10">
            <div>
            <h1><span className='text-7xl desktop:text-8xl text-default font-thin'
            style={{ fontFamily: `${guthen}` }}>Energy</span></h1>
                <h1 className='font-semibold tracking-wide -mt-10 text-4xl'>Efficiency</h1>
            </div>
            <div className="flex-initial w-10/12 tablet:w-7/12">
            <Lottie options={energyOptions} />
            </div>
            <div>
            <p className="mt-6 text-lg tracking-wide font-semibold leading-8 middle:text-left text-center">Smart Home Automation allows everyone to contribute towards a better environment. Our intelligent sensors allow you to save energy whenever you are not at home. And if that’s not enough, you also gain insights into your energy consumption and can personalize schedules accordingly.
                <br /><br />
                Take a step towards a greener lifestyle with intelligent automation.</p>
            </div>
        </div>

            {/* page 7 */}
            <div id="lighting" className='relative lg:min-h-[130vh] h-full flex justify-start items-center'>
                <img className='absolute -z-10 top-0 h-[30vh] left-0 lg:h-[130vh] lg:object-cover w-full' src="https://syncrow.s3.ap-south-1.amazonaws.com/smart_home_lighting_system_controller_f222de75cf.png" alt='' />
                <div className='lg:pl-[8.5%] lg:w-[50%] flex flex-col'>
                    <motion.div
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className='h-[30vh] pt-[10%] lg:pt-0 px-[2rem] lg:px-0 lg:h-auto'>
                        <h3 style={{ fontFamily: `${guthen}` }} className="text-[3.5rem] tablet:pl-10 laptop:pl-0 font-medium text-left leading-[4rem] text-blue-700 mt-[3rem]">Automate</h3>
                        <p className='text-left tablet:pl-10 laptop:pl-0 font-bold text-[1rem] lg:text-[2rem] lg:leading-[1.7rem]'>lobby lights. Save energy</p>
                    </motion.div>
                    <motion.p
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className='text-center py-[1rem] px-[2rem] lg:px-0 lg:text-left'>Turn the lights off or dim them to a minimum, when no one’s around. Get the lobby, basement or parking to light up when someone passes by. Using the simple automation hack, residential/commercial spaces can save up to 80% energy.</motion.p>
                    <motion.div
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className="mt-[2.5rem] lg:px-0 px-[2rem] pb-[2rem] lg:pb-0">
                        <div className="flex mt-[1rem]">
                            <div className="mr-[1rem] flex justify-center items-center">
                                
 <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                            </div>
                            <p className="font-normal mt-2">Ask our expert</p>
                        </div>
                        <div className="flex mt-[1rem]">
                            <div className="mr-[1rem] flex justify-center items-center">
                                
 <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                            </div>
                            <p className="font-normal mt-2">Choose your bundle Or Design your own.</p>
                        </div>
                    </motion.div>
                </div>
            </div>


            {/* page 8 */}
            <div className='relative lg:min-h-[70vh] flex flex-col lg:flex-row'>
                <motion.div
                    initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.5 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}
                    className='lg:w-[50%] flex lg:relative absolute -z-10 lg:h-full h-[50vh] justify-center items-center'>
                    <Lottie style={{ width: "80%", objectFit: "contain" }} options={phoneOptions} />
                    <div className="absolute top-20 middle:block hidden  middle:right-16 medium:right-24 mediumLarge:top-28 mediumLarge:right-32 big:right-40 desktop:right-40">
                    <Lottie options={exclamationOptions} style={{width:"40%",height:"40%"}} />
                    </div>
                </motion.div>
                <div className='lg:w-[40%] flex justify-center items-start lg:pr-[10%] flex-col'>
                    <motion.div
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className='h-[50vh] flex flex-col justify-evenly lg:justify-start lg:h-auto'>
                        <h3 style={{ fontFamily: `${guthen}` }} className="text-[4rem] text-center lg:text-left leading-[4rem] text-blue-700 mt-[3rem]">Get Notified</h3>
                        <p className='text-center lg:text-left font-bold text-[2rem] leading-[1.7rem]'>before intrusion happens</p>
                    </motion.div>
                    <motion.p
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className='text-center lg:px-0 px-[2rem] lg:text-left mt-[2rem]'>Our innovative building security module keeps track of alarm systems installed in every flat/shop of the residential/commercial building and proactively notifies the central security cabin when an intrusion is detected.</motion.p>
                    <motion.div
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className="mt-[2.5rem] lg:px-0 px-[2rem] pb-[2rem] lg:pb-0">
                        <div className="flex mt-[1rem]">
                            <div className="mr-[1rem] flex justify-center items-center">
                                
 <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                            </div>
                            <p className="font-normal mt-2">Ask our expert</p>
                        </div>
                        <div className="flex mt-[1rem]">
                            <div className="mr-[1rem] flex justify-center items-center">
                                
 <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                            </div>
                            <p className="font-normal mt-2">Choose your bundle Or Design your own.</p>
                        </div>
                    </motion.div>
                </div>
            </div>

            {/* page 9 */}
            <div className='relative lg:min-h-[100vh] flex flex-col lg:flex-row'>
                {/* desktop img  */}
                <img className='hidden lg:block lg:absolute -z-10 lg:top-0 lg:left-0 lg:w-full h-[70vh] lg:h-full object-cover' src="https://syncrow.s3.ap-south-1.amazonaws.com/Mask_Group_39_b2da95842e.png" alt='' />
                {/* mobile img  */}
                <img className='block lg:hidden lg:absolute -z-10 lg:top-0 lg:left-0 lg:w-full h-[70vh] lg:h-full object-cover' src="/apartments-page-9-m.png" alt='' />
                <div className='lg:w-[40%] lg:pl-[10%] flex flex-col justify-center'>
                    <motion.h3
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        style={{ fontFamily: `${guthen}` }} className="text-[4rem] px-[2rem] lg:px-0 text-center lg:text-left leading-[4rem] text-blue-700 mt-[3rem]">Open Garage Doors</motion.h3>
                    <motion.p
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className='text-center lg:text-left px-[2rem] lg:px-0 font-bold text-[2rem] leading-[1.7rem]'>from your smartphone</motion.p>
                    <motion.p
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className='lg:text-left text-center px-[2rem] lg:px-0 my-[2rem]'>Provide restricted parking access to residents by using RFID-based entrance systems. or even better, allow them to enter their private parking spaces by simply pressing a button on their smartphone. No keyfob is required.</motion.p>
                    <motion.div
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className="mt-[2.5rem] lg:px-0 px-[2rem] pb-[2rem] lg:pb-0">
                        <div className="flex mt-[1rem]">
                            <div className="mr-[1rem] flex justify-center items-center">
                                
 <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                            </div>
                            <p className="font-normal mt-2">Ask our expert</p>
                        </div>
                        <div className="flex mt-[1rem]">
                            <div className="mr-[1rem] flex justify-center items-center">
                                
 <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                            </div>
                            <p className="font-normal mt-2">Choose your bundle Or Design your own.</p>
                        </div>
                    </motion.div>
                </div>

            </div>

            {/* page 10 */}
            <div className='relative lg:min-h-[80vh] flex lg:flex-row lg:justify-end'>
                {/* desktop img  */}
                <img className='hidden lg:block absolute w-full h-full -z-10 object-cover' src="https://syncrow.s3.ap-south-1.amazonaws.com/Mask_Group_40_a9b74a94f1.png" alt='' />
                {/* mobile img  */}
                <img className=' block lg:hidden absolute w-full h-full -z-10 object-cover' src="/apartments-page-10-m.png" alt='' />
                <div className='lg:w-[40%] pt-[20vh] lg:pt-0 lg:pr-[10%]'>

                    <motion.h3
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        style={{ fontFamily: `${guthen}` }} className=" font-medium text-[4rem] px-[2rem] lg:px-0 text-center lg:text-left leading-[4rem] text-blue-700 mt-[3rem]">Trigger</motion.h3>
                    <motion.p
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className='text-center lg:text-left px-[2rem] lg:px-0 font-bold text-[2rem] lg:leading-[2rem]'>Crisis alarm</motion.p>
                    <motion.p
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className='lg:text-left text-center px-[2rem] lg:px-0 mb-[1rem] lg:mb-auto lg:my-[2rem]'>Prevent damage before it happens. Install fire, smoke, and flood sensors across your building campus, and get instant notifications in case of emergencies. You can even configure proactive damage control by automatically turning off power or gas supply during emergencies.</motion.p>
                    <motion.div
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className="lg:mt-[2.5rem] lg:px-0 px-[2rem] pb-[2rem] lg:pb-0">
                        <div className="flex mt-[1rem]">
                            <div className="mr-[1rem] flex justify-center items-center">
                                
 <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                            </div>
                            <p className="font-normal mt-2">Ask our expert</p>
                        </div>
                        <div className="flex mt-[1rem]">
                            <div className="mr-[1rem] flex justify-center items-center">
                                
 <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                            </div>
                            <p className="font-normal mt-2">Choose your bundle Or Design your own.</p>
                        </div>
                    </motion.div>
                </div>
            </div>

            {/* page 11  */}

            <div className='relative lg:min-h-[70vh] lg:px-[10%] flex flex-col-reverse lg:flex-row lg:justify-center'>
                <div className='lg:w-[50%] lg:pr-[10%]'>
                    <motion.div
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className='lg:h-auto h-[47vh]'>
                        <h3 style={{ fontFamily: `${guthen}` }} className=" font-medium text-[4rem] px-[2rem] lg:px-0 text-center lg:text-left leading-[4rem] text-blue-700 mt-[3rem]">Automate</h3>
                        <p className='text-center lg:text-left px-[2rem] lg:px-0 font-bold text-[1.5rem] leading-[1.7rem]'>Water Management</p>
                    </motion.div>
                    <motion.p
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className='lg:text-left text-center px-[2rem] lg:px-0 my-[2rem]'>Using advanced water level sensors and relays, you can completely automate water management i.e turn on the water pump when the water level is low, and automatically turn it off when the level is high. No human intervention is required.</motion.p>
                    <motion.div
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className="mt-[2.5rem] lg:px-0 px-[2rem] pb-[2rem] lg:pb-0">
                        <div className="flex mt-[1rem]">
                            <div className="mr-[1rem] flex justify-center items-center">
                                
 <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                            </div>
                            <p className="font-normal mt-2">Ask our expert</p>
                        </div>
                        <div className="flex mt-[1rem]">
                            <div className="mr-[1rem] flex justify-center items-center">
                                
 <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                            </div>
                            <p className="font-normal mt-2">Choose your bundle Or Design your own.</p>
                        </div>
                    </motion.div>
                </div>
                <motion.div
                    initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.5 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}
                    className='lg:w-[40%] lg:relative absolute h-[40vh] lg:h-auto top-[15vh] lg:top-0 w-full pt-[10vh] lg:pt-0 flex justify-center items-center'>
                    <Lottie options={waterOptions} style={{ width: "100%", height:"100%", objectFit: "contain" }} />

                </motion.div>
            </div>

            {/* page 12 */}
            <div className='relative lg:min-h-[100vh] flex lg:justify-end'>
                {/* desktop img  */}
                <img className='hidden lg:block absolute w-full -z-10 lg:h-full h-[50vh] object-left object-cover' src='https://syncrow.s3.ap-south-1.amazonaws.com/Mask_Group_41_7cdace5d0d.png' alt='' />
                {/* mobile img  */}
                <img className='block lg:hidden absolute w-full -z-10 lg:h-full h-[50vh] object-left object-cover' src='/apartments-page-12-m.png' alt='' />
                <div className='lg:w-[40%] lg:pl-[2rem] text-white lg:pr-[10%] flex flex-col justify-center lg:bg-[#00000065]'>
                    <motion.div
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.3 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className='lg:h-auto  h-[50vh]'>
                        <h3 style={{ fontFamily: `${guthen}` }} className="text-blue-700 lg:text-white  font-medium text-[4rem] px-[2rem] lg:px-0 text-center lg:text-left leading-[4rem] mt-[3rem]">Keep</h3>
                        <p className='text-center lg:text-left px-[2rem] lg:px-0 font-bold text-[1.5rem] leading-[1.7rem] text-black lg:text-white'>an eye on every floor</p>
                    </motion.div>
                    <div className='bg-[#000] lg:bg-[#00000000]'>
                        <motion.p
                            initial="hidden"
                            whileInView="visible"
                            viewport={{ once: false }}
                            transition={{ duration: 0.3 }}
                            variants={{
                                visible: { opacity: 1, scale: 1 },
                                hidden: { opacity: 0, scale: 0 }
                            }}
                            className='lg:text-left text-center p-[2rem] lg:font-[aftika-extra-light] lg:p-0 my-[2rem]'>Using our advanced cameras, you can keep an eye on every floor, every building across your residential/commercial campus. You can pass on access privileges to residents in the building so that they can give a visual confirmation on visitors and monitor their homes from anywhere in the world.</motion.p>
                        <motion.div
                            initial="hidden"
                            whileInView="visible"
                            viewport={{ once: false }}
                            transition={{ duration: 0.3 }}
                            variants={{
                                visible: { opacity: 1, scale: 1 },
                                hidden: { opacity: 0, scale: 0 }
                            }}
                            className="mt-[2.5rem] lg:px-0 px-[2rem] pb-[2rem] lg:pb-0">
                            <div className="flex mt-[1rem]">
                                <div className="mr-[1rem] flex justify-center items-center">
                                    
 <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                                </div>
                                <p className="font-normal mt-2">Ask our expert</p>
                            </div>
                            <div className="flex mt-[1rem]">
                                <div className="mr-[1rem] flex justify-center items-center">
                                    
 <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                                </div>
                                <p className="font-normal mt-2">Choose your bundle Or Design your own.</p>
                            </div>
                        </motion.div>
                    </div>

                </div>

            </div>

            {/* page13 */}

            <div id="temp" className="py-10 items-center tablet:px-20 bg-cyan-100 px-8 middle:flex hidden">
                <div className="flex-1 ">
                    <div className='h-96'>
                <Lottie
                    options={coldOptions}
                    width={"100%"}
                    height={"80%"}
                
                />
                </div>
                </div>
                <div className="flex-1 text-left">
                <motion.h1  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}  ><span className='text-7xl desktop:text-8xl text-blue-600 font-thin text-left'
            style={{ fontFamily: `${guthen}` }}>Control</span></motion.h1>
           <motion.span  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className="laptop:text-3xl desktop:text-3xl font-bold leading-none">
                        Temperature
                    </motion.span>
                    <motion.p  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className="mt-4  font-[aftika-light] tracking-wide leading-7 text-base text-left ">Integrate the air-conditioning and ventilation to a coherent and efficient climate control. Measured temperature values in the lobby and communal areas are supplied to the climate control to generate the optimum temperature.
                    
                    </motion.p>
                </div>
            </div>


            <div className="middle:hidden flex flex-col tablet:px-20 px-8 bg-cyan-100">
            <div className="flex-1 flex items-center justify-center">
                <div className=''>
                <Lottie
                    options={coldOptions}
                    width={"100%"}
                    objectFit={'contain'}
                    height="80%"
                />
                </div>
                </div>
                <div className="flex-1 text-center mb-10 mt-10 tablet:-mt-56 laptop:-mt-72 z-10">
                <h1><span className='text-7xl desktop:text-8xl text-default font-thin text-center'
            style={{ fontFamily: `${guthen}` }}>Control</span></h1>
                <h1><span className='text-3xl desktop:text-8xl font-thin text-center'>Temperature</span></h1>
                    <p className="tablet:mt-36  font-[aftika-light] tracking-wide leading-7 text-base text-center ">Integrate the air-conditioning and ventilation to a coherent and efficient climate control. Measured temperature values in the lobby and communal areas are supplied to the climate control to generate the optimum temperature.</p>
                </div>
            </div>


            <Footer />
        </>
    )
}

export default Apartment;