/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */
import Header from "../components/header";
import Footer from "../components/footer";
import ProvideConvenience from "../components/ProvideConvenience";
import Head from "next/head";
import Lottie from "react-lottie";
import circleAnimation from "./lotties/circle.json";
import "react-responsive-carousel/lib/styles/carousel.min.css";
import { Carousel } from "react-responsive-carousel";
import React, { useState, useEffect } from "react";
import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import "swiper/css/pagination";
import { Pagination } from "swiper";
import Link from "next/link";
import {
  Link as ScrollLink,
  DirectLink,
  Element,
  Events,
  animateScroll as scroll,
  scrollSpy,
  scroller,
} from "react-scroll";

import "swiper/css";
import "swiper/css/pagination";
import HomeBanner from "../components/HomeBanner";
import styles from "../styles/Home.module.css";
import AutomateHome from "../components/AutomateHome";
import Salesiq from "./salesiq";

export async function getStaticProps() {
  const res = await fetch(
    "https://syncrow.kodagu.today/api/homepage?populate[0]=slider&populate[1]=slider.cover&populate[2]=page2_cover&populate[3]=blue_row_feature&populate[4]=blue_row_feature.cover&populate[5]=house_feature&populate[6]=house_feature.cover&populate[7]=page5_cover&populate[8]=page5_offer_cover&populate[9]=testimonial_card&populate[10]=testimonial_card.cover"
  );
  const response = await res.json();
  var data = response.data.attributes;
  return {
    props: {
      data,
    },
  };
}


export default function Home({ data }) {
  const [active, setActive] = useState(0);
  const [page, setpage] = useState(0);
  const defaultOptions = {
    loop: true,
    autoplay: true,
    animationData: circleAnimation,
    rendererSettings: {
      preserveAspectRatio: "xMidYMid slice",
    },
  };
  var changePage = (option) => {
    var newpage = page;
    if (option === "next") {
      newpage = page + 1;
      setpage(newpage);
      scroller.scrollTo(newpage.toString(), {
        duration: 800,
        delay: 0,
        smooth: "easeInOutQuart",
      });
    } else if (option === "prev") {
      newpage = page - 1;
      setpage(newpage);
      scroller.scrollTo(newpage.toString(), {
        duration: 800,
        delay: 0,
        smooth: "easeInOutQuart",
      });
    }
  };
  useEffect(() => {
    changePage();
  });
  const guthen = "Guthen Bloots Personal Use";

  return (
    <div className="overflow-x-hidden">
      <Head>
        <title>Syncrow</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://ik.imagekit.io/jason7531/syncrow/common/Group_1_rkAObjd65.png?ik-sdk-version=javascript-1.4.3&updatedAt=1642343317149"
        />
        <style>
          @import
          url(https://fonts.cdnfonts.com/css/guthen-bloots-personal-use);
        </style>
      </Head>
     
      {/* <Salesiq widgetCode={"5d136296e304ee64ead63634da3bd69f3b95c4131260019df2489d69ced4eb0ffa14704ef2df77eda1b54c0e181d4d05"} domain={"https://salesiq.zoho.com/widget"} /> */}
      
      <Element name="0">
        
        <div className="h-screen relative">
          <Header color="white" />
          {/* <Carousel
            infiniteLoop
            autoPlay={true}
            showStatus={false}
            showIndicators={true}
            showArrows={false}
            showThumbs={false}
          >
            {data.slider.map((element, index) => {
              return (
                <div key={index}>
                  <img src={element.cover.data.attributes.url} />
                  <div className='text-white absolute text-left top-0 left-0 w-full flex justify-center h-full items-center gap-10'>
                    
                    <div className='flex items-end gap-10 relative bottom-[7.5rem]'>
                      <h1
                        className='laptop:text-9xl desktop:text-10xl'
                        style={{ fontFamily: `${guthen}` }}
                      >
                        Effortlessly
                      </h1>
                      <div className='text-5xl'>
                        <p>smart,</p>
                        <p className='-mt-6'>convenient</p>
                      </div>
                    </div>
                    <div className='relative top-40'>
                      <h1 className='text-5xl font-semibold'>
                        {element.title_opener_1}
                      </h1>
                      <h1 className='text-5xl font-semibold -mt-4'>
                        {element.title_opener_2}
                      </h1>
                      <p className='mt-3 text-xl font-thin'>
                        {element.sub_opener}
                      </p>
                      <div className='flex items-center gap-3'>
                        <p>{element.three_word_separated.split(',')[0]} </p>
                        <span className='text-default text-3xl'>|</span>{' '}
                        <p>{element.three_word_separated.split(',')[1]}</p>
                        <span className='text-default text-3xl'>|</span>{' '}
                        <p>{element.three_word_separated.split(',')[2]}</p>
                      </div>
                    </div>
                  </div>
                </div>
              );
            })}
          </Carousel> */}
          <div className="">
            <Carousel
              infiniteLoop
              autoPlay={true}
              showStatus={false}
              showIndicators={true}
              showArrows={false}
              showThumbs={false}
              swipeable={false}

              renderArrowPrev={(clickHandler, hasPrev, labelPrev) => {
                return (
                  <button className="text-white text-[1.5rem] lg:text-[2rem] absolute z-10 lg:left-[5%]  left-[2%] top-[50%]" onClick={clickHandler}>
                    <i className="fa-solid fa-angle-left"></i>
                  </button>
                )
              }}
              renderArrowNext={(clickHandler, hasPrev, labelPrev) => {
                return (
                  <button className="text-white text-[1.5rem] lg:text-[2rem] absolute z-10 lg:right-[5%] right-[2%] top-[50%]" onClick={clickHandler}>
                    <i className="fa-solid fa-angle-right"></i>
                  </button>
                )
              }}
            >
              {data.slider.map((element, index) => {
                return (
                  <div
                    key={index}
                    className="w-[100%] h-[100vh] max-h-1500 relative flex justify-center items-center"
                  >
                    {/* desktop img  */}
                    <img
                      className="hidden lg:block -z-10 absolute w-[100%] h-[100%] object-cover"
                      src={element.cover.data.attributes.url}
                      alt="..."
                    />
                    {/* mobile img 
                    <img className='hidden lg:hidden -z-10 absolute w-[100%] h-[100%]' src={index === 0 ? "/carousel-1-m.png" : index === 1 ? "/carousel-2-m.png" : "/carousel-3-m.png"} alt='...' /> */}
                    <div className="flex flex-col lg:pt-[20vh] items-end w-[100%] lg:w-[80%] text-white p-[2rem] lg:p-0">
                      <div className="flex items-center w-[100%] lg:mb-0 mb-[3rem]">
                        <p
                          style={{ fontFamily: `${guthen}` }}
                          className="text-[3rem] lg:w-[50%] lg:text-right lg:text-[7rem] "
                        >
                          Effortlessly
                        </p>
                        <span className="text-[1rem] lg:text-[3rem] items-center lg:w-[50%] lg:text-left lg:leading-none lg:pt-8 tracking-wide text-left pl-3 font-light ">
                          smart,
                          <br />
                          convenient
                        </span>
                      </div>
                      <div className="flex lg:w-[50%] flex-col lg:pl-3 lg:pt-8">
                        <p className="text-[2.3rem] leading-tight tracking-widest mb-5 text-left font-semibold">
                          {element.title_opener_1} {element.title_opener_2}
                        </p>
                        <p className="text-left text-[.9rem] font-[aftika-extra-light] tracking-wide lg:pb-2">
                          {element.sub_opener}
                        </p>
                        <p className="text-left font-bold tracking-widest">
                          {element.three_word_separated.split(",")[0] ===
                            "AC" ? (
                            <Link href="/home/convenience#climateControl">
                              {element.three_word_separated.split(",")[0]}
                            </Link>
                          ) : (
                            ""
                          )}
                          {element.three_word_separated.split(",")[0] ===
                            "Media" ? (
                            <Link href="/home/accessibility#multimedia">
                              {element.three_word_separated.split(",")[0]}
                            </Link>
                          ) : (
                            ""
                          )}
                          {element.three_word_separated.split(",")[0] ===
                            "Alarm" ? (
                            <Link href="/home/security#protection">
                              {element.three_word_separated.split(",")[0]}
                            </Link>
                          ) : (
                            ""
                          )}
                          <span className="text-blue-900 mx-[.8rem]">|</span>

                          {element.three_word_separated.split(",")[1] ==
                            "Heater" ? (
                            <Link href="/home/convenience#heater">
                              {element.three_word_separated.split(",")[1]}
                            </Link>
                          ) : (
                            ""
                          )}
                          {element.three_word_separated.split(",")[1] ===
                            "Curtains" ? (
                            <Link href="/home/convenience#homeConvenience">
                              {element.three_word_separated.split(",")[1]}
                            </Link>
                          ) : (
                            ""
                          )}
                          {element.three_word_separated.split(",")[1] ===
                            "Camera" ? (
                            <Link href="/home/security#monitor">
                              {element.three_word_separated.split(",")[1]}
                            </Link>
                          ) : (
                            ""
                          )}

                          <span className="text-blue-900 mx-[.8rem]">|</span>

                          {element.three_word_separated.split(",")[2] ===
                            "Lighting" ? (
                            <Link href="/home/convenience#smartLightingPrev">
                              {element.three_word_separated.split(",")[2]}
                            </Link>
                          ) : (
                            ""
                          )}
                          {element.three_word_separated.split(",")[2] ===
                            "Hub" ? (
                            <Link href="/home/accessibility#homeAccessibility">
                              {element.three_word_separated.split(",")[2]}
                            </Link>
                          ) : (
                            ""
                          )}
                          {element.three_word_separated.split(",")[2] ===
                            "Doorlock" ? (
                            <Link href="/home/security#doorLock">
                              {element.three_word_separated.split(",")[2]}
                            </Link>
                          ) : (
                            ""
                          )}

                        </p>
                      </div>
                    </div>
                  </div>
                );
              })}
            </Carousel>
          </div>
        </div>
      </Element>

      {/*page2*/}
      <Element name="1">
        <HomeBanner />
      </Element>

      {/* page4 */}
      <Element name="3">
        <AutomateHome />
      </Element>

      {/*page5*/}

      {/* <Element name="4"></Element> */}

      {/*page5*/}
      {/*page3*/}
      <Element name="2">
        <div className="tablet:mx-20 -mt-5 mx-10 mb-24">
          <div className="laptop:flex items-center justify-center mb-2 hidden">
            <h1 className="tablet:text-5xl text-4xl">
              {" "}
              <span
                className="tablet:text-6xl text-5xl"
                style={{ fontFamily: `Guthen Bloots Personal Use` }}
              >
                Worry
              </span>{" "}
              less with wireless
            </h1>
          </div>
          <div className="flex laptop:hidden items-center justify-center mb-2 mt-16">
            <h1 className="text-2xl">
              {" "}
              <span className="tablet:text-7xl extrasmall:text-6xl text-3xl">
                Worry
              </span>{" "}
              less with wireless
            </h1>
          </div>
          {/* desktop */}

          <div className="gap-8 middle:flex hidden desktop:mx-56">
            <div className="tablet:w-1/3 w-full">
              <img
                src="https://syncrow.s3.ap-south-1.amazonaws.com/Mask_Group_1_0_G4_OZ_d_A2_W3_73941d0700.webp"
                className="w-full desktop:h-98 h-80 object-cover rounded-t-3xl"
                alt=""
              />
              <div className="bg-blue-700 -mt-2 rounded-b-3xl desktop:h-85 mediumLarge:h-98  medium:h-99 relative  h-[495px]">
                <h2 className="uppercase pt-6 pb-2 text-white px-8 text-3xl font-semibold">
                  convenience
                </h2>
                <div className="px-8 text-white">
                  <p className=" pb-4 text-tiny font-[aftika-light] tracking-wide">
                    Syncrow provides just that with an easy installation.
                  </p>

                  <p className="text-tiny font-[aftika-light] pb-4 tracking-wide">
                    {" "}
                    A smart home adds more to your life, making it more
                    convenient, safe, and comfortable.
                  </p>

                  <p className="text-tiny font-[aftika-light] pb-4 tracking-wide">
                    {" "}
                    Connect your home to an easy-to-use system without the
                    hassle of rewiring or remodelling your internal wiring.
                  </p>

                  <p className="text-tiny font-[aftika-light] pb-4 tracking-wide">
                    Worry less and upgrade your home effortlessly.
                  </p>
                </div>
                <button className="capitalize mx-8 bg-white text-blue-700 rounded-lg py-2 px-6 my-8 absolute bottom-0  font-[aftika-bold]">
                  ask an expert
                </button>
              </div>
            </div>
            <div className="tablet:w-1/3 w-full  ">
              <img
                src="https://syncrow.s3.ap-south-1.amazonaws.com/Mask_Group_2_2i_LOW_4_Eh_QDY_382f6bb39b.webp"
                className="w-full desktop:h-98 h-80 object-cover rounded-t-3xl"
                alt=""
              />
              <div className="bg-blue-700 -mt-2 rounded-b-3xl desktop:h-85 medium:h-99  mediumLarge:h-98  relative h-[495px]">
                <h2 className="uppercase  pt-6 pb-2 text-white px-8 text-3xl font-semibold">
                  SAFETY
                </h2>
                <div className="px-8 text-white">
                  <p className="text-tiny font-[aftika-light] tracking-wide pb-4 ">
                    An intelligent space keeps you informed, always. (real-time
                    to be incorporated)
                  </p>
                  <p className="text-tiny font-[aftika-light] tracking-wide pb-4">
                    Stay in control of what’s happening in your home from
                    anywhere in the world.
                  </p>
                  <p className="text-tiny font-[aftika-light] tracking-wide pb-4">
                    Empower yourself to relax a bit with convenient remote
                    access to cameras, door locks, alarms, and alerts.
                  </p>
                  <p className="text-tiny font-[aftika-light] tracking-wide pb-4">
                    Worry less and experience safety delivered, effortlessly.
                  </p>
                </div>
                <button className="capitalize mx-8 bg-white text-blue-700 rounded-lg py-2 px-6 my-8 absolute bottom-0  font-[aftika-bold]">
                  ask an expert
                </button>
              </div>
            </div>
            <div className="tablet:w-1/3 w-full ">
              <img
                src="https://syncrow.s3.ap-south-1.amazonaws.com/Image_3_db67fdaaef.png"
                className="w-full desktop:h-98 h-80 object-cover rounded-t-3xl"
                alt=""
              />
              <div className="bg-blue-700 -mt-2 rounded-b-3xl desktop:h-85 medium:h-99 mediumLarge:h-98 relative h-[495px]">
                <h2 className="uppercase  pt-6 pb-2  text-white px-8 text-3xl font-semibold">
                  save energy
                </h2>
                <div className="px-8 text-white">
                  <p className="text-tiny font-[aftika-light] tracking-wide pb-4">
                    It’s just sensible to be energy efficient. Seamlessly
                    integrated with your space, operate them more efficiently.
                  </p>
                  <p className="text-tiny font-[aftika-light] tracking-wide pb-4">
                    Leverage the power of IoT and save up by setting up smart
                    schedules for your lights, AC, Water Heater, and more.
                  </p>
                  <p className="text-tiny font-[aftika-light] tracking-wide pb-4">
                    Worry less and start saving up, effortlessly.
                  </p>
                </div>
                <button className="capitalize mx-8 bg-white text-blue-700 rounded-lg py-2 px-6 my-8 absolute bottom-0 font-[aftika-bold]">
                  ask an expert
                </button>
              </div>

              {/* desktop */}
            </div>
            {/* mobile */}
          </div>

          <div className="middle:hidden flex middle:rounded-none rounded-b-3xl">
            <Swiper
              modules={[Pagination]}
              className={`${styles.swiper} mySwiper`}
              showsPagination={false}
            >
              <SwiperSlide>
                <div className="flex items-center justify-center h-107 rounded-2xl">
                  <div className="w-full tablet:w-3/4 h-full rounded-b-3xl">
                    <img
                      src="https://syncrow.s3.ap-south-1.amazonaws.com/Mask_Group_1_0_G4_OZ_d_A2_W3_73941d0700.webp"
                      className="w-full"
                      alt=""
                    />
                    <div className="bg-blue-700 -mt-2 rounded-b-3xl flex flex-col items-center h-[495px]">
                      <h2 className="uppercase py-10 text-white px-8 text-3xl font-semibold tracking-wide">
                        convenience
                      </h2>
                      <div className="px-8 text-white">
                        <p className=" text-tiny font-[aftika-light] tracking-wide pb-2 text-center">
                          Syncrow provides just that with an easy installation.
                        </p>

                        <p className=" text-tiny font-[aftika-light] tracking-wide pb-2 text-center">
                          {" "}
                          A smart home adds more to your life, making it more
                          convenient, safe, and comfortable.
                        </p>

                        <p className=" text-tiny font-[aftika-light] tracking-wide pb-2 text-center">
                          {" "}
                          Connect your home to an easy-to-use system without the
                          hassle of rewiring or remodelling your internal
                          wiring.
                        </p>

                        <p className=" text-tiny font-[aftika-light] tracking-wide pb-2 text-center">
                          Worry less and upgrade your home effortlessly.
                        </p>
                      </div>

                      <button className="capitalize mx-8 bg-white text-blue-700 rounded-lg py-2 px-6 my-8 font-bold">
                        ask an expert
                      </button>
                    </div>
                  </div>
                </div>
              </SwiperSlide>
              <SwiperSlide>
                <div className="flex items-center justify-center rounded-2xl">
                  <div className="w-full tablet:w-3/4 rounded-b-2xl h-full">
                    <img
                      src="https://syncrow.s3.ap-south-1.amazonaws.com/Mask_Group_2_2i_LOW_4_Eh_QDY_382f6bb39b.webp"
                      className="w-full"
                      alt=""
                    />
                    <div className="bg-blue-700 -mt-2 rounded-b-3xl flex flex-col items-center h-[495px]">
                      <h2 className="uppercase py-10 text-white px-8 text-3xl font-semibold tracking-wide">
                        safety
                      </h2>
                      <div className="px-8 text-white">
                        <p className=" text-tiny font-[aftika-light] tracking-wide pb-2 text-center">
                          An intelligent space keeps you informed, always.
                          (real-time to be incorporated)
                        </p>
                        <p className=" text-tiny font-[aftika-light] tracking-wide pb-2 text-center">
                          Stay in control of what’s happening in your home from
                          anywhere in the world.
                        </p>
                        <p className="text-tiny font-[aftika-light] tracking-wide pb-2 text-center">
                          Empower yourself to relax a bit with convenient remote
                          access to cameras, door locks, alarms, and alerts.
                        </p>
                        <p className=" text-tiny font-[aftika-light] tracking-wide pb-2 text-center">
                          Worry less and experience safety delivered,
                          effortlessly.
                        </p>
                      </div>
                      <button className="capitalize mx-8 bg-white text-blue-700 rounded-lg py-2 px-6 my-8 font-bold">
                        ask an expert
                      </button>
                    </div>
                  </div>
                </div>
              </SwiperSlide>
              <SwiperSlide>
                <div className="flex items-center justify-center rounded-2xl">
                  <div className="w-full tablet:w-3/4 h-full">
                    <img
                      src="https://syncrow.s3.ap-south-1.amazonaws.com/Image_3_db67fdaaef.png"
                      className="w-full"
                      alt=""
                    />
                    <div className="bg-blue-700  -mt-2 rounded-b-3xl flex flex-col items-center h-[495px]">
                      <h2 className="uppercase py-10 text-white px-8 text-3xl font-semibold text-center tracking-wide">
                        save energy
                      </h2>
                      <div className="px-8 text-white text-center">
                        <p className=" text-tiny font-[aftika-light] tracking-wide pb-2 text-center">
                          It’s just sensible to be energy efficient. Seamlessly
                          integrated with your space, operate them more
                          efficiently.
                        </p>
                        <p className=" text-tiny font-[aftika-light] tracking-wide pb-2 text-center">
                          Leverage the power of IoT and save up by setting up
                          smart schedules for your lights, AC, Water Heater, and
                          more.
                        </p>
                        <p className="text-tiny font-[aftika-light] tracking-wide pb-2 text-center">
                          Worry less and start saving up, effortlessly.
                        </p>
                      </div>
                      <button className="capitalize mx-8 bg-white text-blue-700 rounded-lg py-2 px-6 my-8 text-center font-bold">
                        ask an expert
                      </button>
                    </div>
                  </div>
                </div>
              </SwiperSlide>
            </Swiper>
          </div>
        </div>
      </Element>


      <Element name="4">
        {/* desktop  */}
        <ProvideConvenience />
      </Element>

      {/*page6 testimonials*/}
      <Element name="5">
        {" "}
        <div className="mt-60 mb-14 container px-4 md:px-24 mx-auto ">
          <span
            className="text-5xl text-center md:text-right mb-5"
            style={{ fontFamily: `${guthen}` }}
          >
            {data.testimonial_page_title}
          </span>

          <Swiper
            modules={[Pagination]}
            showsPagination={false}
            spaceBetween={50}
            slidesPerView={1}
            breakpoints={{
              600: {
                slidesPerView: 2,
                spaceBetween: 30,
              },
              1024: {
                slidesPerView: 3,
                spaceBetween: 30,
              },
            }}
            onSlideChange={() => console.log("slide change")}
            className="grid grid-cols-3 gap-5 "
          >
            {data.testimonial_card.slice(0, 6).map((element, index) => {
              return (
                <SwiperSlide
                  key={index.toString()}
                  className="laptop:text-sm leading-6 desktop:text-base"
                >
                  <img src={element.cover.data.attributes.url} />
                  <br />
                  <span className=""> {element.summary} </span>
                </SwiperSlide>
              );
            })}
          </Swiper>
        </div>
      </Element>
      <Footer />
    </div>
  );
}
