import { motion } from "framer-motion";
import Head from "next/head";
import Footer from "../components/footer";
import Header from '../components/header';
import bulbAnimation from './lotties/bulb-workspace.json';
import Lottie from 'react-lottie';
import contactExpertAnimation from "../pages/lotties/ask-your-expert.json"

const Workspace = () => {

    const guthen = 'Guthen Bloots Personal Use';
    const bulbOptions = {
        loop: true,
        autoplay: true,
        animationData: bulbAnimation,
        rendererSettings: {
            preserveAspectRatio: 'xMidYMid meet',
        },
    };
    const contactExpertOptions = {
        loop: true,
        autoplay: true,
        animationData: contactExpertAnimation,
        renderedSettings: {
            // preserveAspectRatio:'xMidYMid slice'
        },
    };
    return (
        <div>
            <Head>
                <title>Syncrow</title>
                <meta name='description' content='Generated by create next app' />
                <link
                    rel='icon'
                    href='https://ik.imagekit.io/jason7531/syncrow/common/Group_1_rkAObjd65.png?ik-sdk-version=javascript-1.4.3&updatedAt=1642343317149'
                />
                {/* guthen font  */}
                <link href="https://fonts.cdnfonts.com/css/guthen-bloots-personal-use" rel="stylesheet" />


                {/* poppins font  */}
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
                <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet" />
                {/* fontawesome */}
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossOrigin="anonymous" referrerpolicy="no-referrer" />
            </Head>
            <Header color='black' />

            {/* page 1 */}
            <div className="relative w-[100%] h-[100vh] max-h-[1500px] overflow-hidden">
                {/* desktop img  */}
                <img className="hidden lg:block absolute top-0 left-0 w-full h-full -z-10 object-cover" src="https://syncrow.s3.ap-south-1.amazonaws.com/Mask_Group_50_96d4e6591c.png" alt="..." />
                {/* mobile img  */}
                <img className="block lg:hidden absolute top-0 left-0 w-full h-full -z-10 object-cover" src="/workspace-page-1-m.png" alt="..." />
                <motion.p
                    initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.3 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}
                    style={{ fontFamily: `${guthen}` }} className=" font-[aftika-semibold] absolute text-[4rem] px-[1rem] lg:px-0 text-center top-[40%] lg:w-[35%] lg:top-[65%] medium:top-[70%] lg:left-[5%]">Give your <span className="text-blue-700 lg:text-black">workplace</span> the competitive edge it needs</motion.p>
            </div>

            {/* page 2 */}

            <div className="relative flex-col lg:flex w-[100%] lg:h-[100vh] justify-between lg:overflow-hidden">
                <img className="absolute top-0 left-0 w-full h-[80vh] lg:h-full -z-10 object-cover" src="https://ik.imagekit.io/jason7531/syncrow/workspace/Mask_Group_42_VRYA6BYSv.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1642306939750" alt="..." />
                <div className="lg:w-[58%] w-[100%] h-[80vh] lg:h-full relative flex-col justify-center items-center lg:pl-[8rem] lg:bg-[#00000065] lg:pt-[10%]">
                    <motion.div
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.5 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className="p-[2rem] lg:p-0">
                        <h3 style={{ fontFamily: `${guthen}` }} className=" font-medium text-blue-700 text-[2.5rem] lg:text-left text-center lg:text-[4rem]">Automate Office spaces = </h3>
                        <h3 style={{ fontFamily: `${guthen}` }} className=" font-medium pl-[2rem] text-blue-700 lg:text-white text-[2.5rem] lg:text-left text-center lg:text-[4rem]">Awesome Office spaces</h3>
                    </motion.div>
                    <motion.div
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.5 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className="mt-[5%] lg:w-[80%] p-[2rem] lg:relative absolute bottom-0 lg:p-0 w-[100%] lg:text-[1rem] text-[.9rem] bg-[#00000065] lg:bg-[#00000000]">
                        <p className="text-white tracking-wide leading-7 font-[aftika-light] lg:text-left text-center">Create a connected workspace that allows you to focus your energies on putting out brilliant ideas rather than worrying about your operational elements. Connect your functional elements, from lighting to projector screens and security, to a network for unparalleled convenience.</p>
                        <p className="pt-[3%] tracking-wide leading-7 font-[aftika-light] text-white  lg:text-left text-center">Setup complex functionalities with ease for mind-blowing presentations, professional meetings, and success parties. With our retrofit, wireless automation, you can turn your office space into the residence of success in just three hassle-free steps without any remodeling or rewiring.</p>
                    </motion.div>
                </div>
                <motion.div
                    initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.3 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}
                    className="lg:w-[40%] mt-[2rem] lg:mt-0 w-[100%] relative h-max lg:absolute lg:right-0 lg:bottom-[8%] px-[2rem] flex-col justify-start">
                    <h3 className=" text-[1.5rem] leading-[1.9rem] font-[aftika-bold] lg:text-[1rem] text-center lg:text-left tracking-wide">Make your <span style={{ fontFamily: `${guthen}` }} className="text-blue-700 text-[3rem]">&nbsp;Workspace </span> work for you</h3>
                    <div className="flex mt-[1rem]">
                        <div className="mr-[1rem] flex justify-center items-center">      <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    /></div>
                        <p className="font-normal tracking-wide text-base leading-7 font-[aftika-light]">Ask our expert</p>
                    </div>
                    <div className="flex mt-[1rem]">
                        <div className="mr-[1rem] flex justify-center items-center">      <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    /></div>
                        <p className="font-normal tracking-wide text-base leading-7 font-[aftika-light]">Choose your bundle Or Design your own.</p>
                    </div>
                </motion.div>
            </div>

            {/* page 3 */}
            <div className="relative flex-col lg:flex mt-[1rem] lg:mt-0 w-[100%] lg:h-[100vh] justify-between lg:overflow-hidden">
                <img className="lg:absolute lg:top-0 lg:left-0 w-full lg:h-full -z-10 object-cover" src="https://syncrow.s3.ap-south-1.amazonaws.com/Mask_Group_43_605f0e9f1a.png" alt="..." />
                <div className="lg:w-[50%] h-[100%] lg:pl-[10%] flex flex-wrap items-center">
                    <motion.div
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.5 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className="lg:mt-0 mt-[1rem] p-[2rem] lg:p-0">
                        <p className="text-[.9rem] lg:text-left text-center lg:text-[1.2rem]">A workplace that invests in crafting a comfort-driven environment makes its employees feel inspired and motivated to work. And Syncrow Smart Workplace Automation takes it to the next level.</p>
                        <p className="text-[.9rem] lg:text-left text-center lg:text-[1.2rem] mt-[2rem]">A workplace that invests in crafting a comfort-driven environment makes its employees feel inspired and motivated to work. And Syncrow Smart Workplace Automation takes it to the next level.</p>
                    </motion.div>
                    <div className="flex-col justify-start lg:p-0 p-[2rem] w-full">
                        <motion.h3
                            initial="hidden"
                            whileInView="visible"
                            viewport={{ once: false }}
                            transition={{ duration: 0.3 }}
                            variants={{
                                visible: { opacity: 1, scale: 1 },
                                hidden: { opacity: 0, scale: 0 }
                            }}
                            className="font-[aftika-semibold] lg:text-[1.1rem] text-center lg:text-left">Make an impression with your</motion.h3>
                        <motion.h3
                            initial="hidden"
                            whileInView="visible"
                            viewport={{ once: false }}
                            transition={{ duration: 0.3 }}
                            variants={{
                                visible: { opacity: 1, scale: 1 },
                                hidden: { opacity: 0, scale: 0 }
                            }}
                            className="font-[aftika-semibold] lg:text-[1.8rem] text-center lg:text-left"><span style={{ fontFamily: `${guthen}, Poppins` }} className="text-blue-700 text-[4rem]">Work</span><span className="text-sm font-[aftika-semibold] ">&nbsp; and &nbsp;</span> <span style={{ fontFamily: `${guthen}, Poppins` }} className="text-blue-700 text-[4rem]">Workplace</span></motion.h3>
                        <motion.div
                            initial="hidden"
                            whileInView="visible"
                            viewport={{ once: false }}
                            transition={{ duration: 0.3 }}
                            variants={{
                                visible: { opacity: 1, scale: 1 },
                                hidden: { opacity: 0, scale: 0 }
                            }}
                            className="flex mt-[1rem]">
                            <div className="mr-[1rem] flex justify-center items-center">
                            <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                            </div>
                            <p className="font-normal leading-7 text-base tracking-wide font-[aftika-light]">Ask our expert</p>
                        </motion.div>
                        <motion.div
                            initial="hidden"
                            whileInView="visible"
                            viewport={{ once: false }}
                            transition={{ duration: 0.3 }}
                            variants={{
                                visible: { opacity: 1, scale: 1 },
                                hidden: { opacity: 0, scale: 0 }
                            }}
                            className="flex mt-[1rem]">
                            <div className="mr-[1rem] flex justify-center items-center">
                            <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                            </div>
                            <p className="font-normal leading-7 text-base tracking-wide font-[aftika-light]">Choose your bundle Or Design your own.</p>
                        </motion.div>
                    </div>
                </div>
            </div>

            {/* page 4 */}
            <div className="bg-blue-700 text-white lg:flex flex-auto py-[4rem]">
                <motion.div
                    initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.3 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}
                    className="lg:w-[50%] flex justify-center items-center">
                    <h2
            className="text-white text-center md:text-left flex flex-col mx-10 leading-none"
            style={{ fontFamily: `${guthen}` }}
          >
            <motion.span  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.3 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }} className="text-5xl lg:text-7xl -mb-10 -ml-28 text-center">Why</motion.span>
            <motion.span  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.3 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }} className="text-6xl lg:text-10xl -ml-10 text-center">Upgrade</motion.span>
            <motion.span  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.3 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }} className="text-5xl lg:text-7xl text-center">To a smarter home?</motion.span>
          </h2>
                </motion.div>
                <div className="lg:w-[50%] flex-col lg:px-[5%] p-[2rem] lg:p-0 mt-[1rem] lg:mt-0 justify-center items-center">
                    <motion.p
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.5 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className="text-center lg:text-left mb-[2rem]  leading-7 text-base tracking-wide font-[aftika-light]">Make your workplace a statement along with your work. While every business has unique propositions, very few focus on creating initial impressions driven by their work environment.</motion.p>
                    <motion.p
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.5 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className="text-center lg:text-left  leading-7 text-base tracking-wide font-[aftika-light]">Take the opportunity to show a bit of your work culture, your passion, and your creativity with office automation. Use your work environment to build a lasting impression among your visitors, while also reducing losses and optimized operational costs.</motion.p>
                    <motion.p
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.5 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className="text-center lg:text-left mt-[2rem]  leading-7 text-base tracking-wide font-[aftika-light]">While everyone focuses on reinventing their aesthetics, ace them with an office that is a high-tech playground.</motion.p>
                </div>
            </div>

            {/* page 5 */}
            <div className="relative flex flex-wrap lg:min-h-[100vh] lg:justify-end">
                {/* desktop image  */}
                <img className="hidden lg:block lg:absolute lg:top-0 lg:left-0 w-full h-[40vh] lg:h-full -z-10 object-cover" src="https://syncrow.s3.ap-south-1.amazonaws.com/Mask_Group_44_ca8a972d11.png" alt="..." />
                {/* mobile image  */}
                <img className="block lg:hidden lg:absolute lg:top-0 lg:left-0 w-full h-[50vh] lg:h-full -z-10 object-cover" src="/workspace-page-5-m.png" alt="..." />
                <div className="flex-col my-auto justify-center items-center lg:w-[40%] lg:pt-0 pt-[2rem] lg:pr-[5%]">
                    <motion.p
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.5 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        style={{ fontFamily: `${guthen}` }} className=" font-[aftika-semibold] px-[2rem] lg:px-0 text-[4.1rem] text-center lg:text-left text-blue-700">Make your Presentation</motion.p>
                    <motion.p
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.5 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className="text-[1.7rem] font-[aftika-bold] -mt-6 text-center lg:text-left">Stand out</motion.p>
                    <motion.div

                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.5 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className="my-[2.5rem]  lg:px-0 px-[2rem]">
                        <p className="text-center  leading-7 text-base tracking-wide font-[aftika-light] lg:text-left">Usually, it takes a few minutes to turn on the projector, pull down the screen and get your presentation up and running. But what if you could ditch the time, and have everything ready at the press of a button?</p>
                        <p className="text-center leading-7 text-base tracking-wide mt-[1.5rem] lg:text-left">Make a bold statement with our innovative, wireless automation technology that can run complex manual tasks, through voice, gesture, or smartphone interactions.</p>
                    </motion.div>
                    <motion.div
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.5 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className="mt-[2.5rem] lg:px-0 px-[2rem] pb-[2rem] lg:pb-0">
                        <div className="flex mt-[1rem]">
                            <div className="mr-[1rem] flex justify-center items-center">
                                {/* lottie */}
                                <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                            </div>
                            <p className="font-normal leading-7 text-base tracking-wide font-[aftika-light]">Ask our expert</p>
                        </div>
                        <div className="flex mt-[1rem]">
                            <div className="mr-[1rem] flex justify-center items-center">
                            {/* lottie */}
                            <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                            </div>
                            <p className="font-normal leading-7 text-base tracking-wide font-[aftika-light]">Choose your bundle Or Design your own.</p>
                        </div>
                    </motion.div>
                </div>
            </div>

            {/* page 6 */}
            <div className="relative flex flex-wrap lg:min-h-[100vh] text-white">
                {/* desktop img  */}
                <img className="hidden lg:block absolute top-0 left-0 w-full h-full -z-10 object-cover" src="https://syncrow.s3.ap-south-1.amazonaws.com/Mask_Group_45_74aac642e4.png" alt="..." />
                {/* mobile img  */}
                <img className="block lg:hidden absolute top-0 left-0 w-full h-full -z-10 object-cover" src="/workspace-page-6-m.png" alt="..." />
                <div className="flex flex-col justify-center lg:pl-[5%] w-[100%] lg:w-[35%]">
                    <motion.div
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.5 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className="p-[2rem] lg:p-0">
                        <p style={{ fontFamily: `${guthen}` }} className="text-[4rem] text-center lg:text-left mt-24">Order Coffee</p>
                        <p className="text-[1.8rem] font-[aftika-semibold] text-center lg:text-left leading-[2rem]">From Your Desk</p>
                    </motion.div>
                    <div className="lg:my-[3rem] lg:bg-[#00000000] bg-[#00000065] lg:p-0 lg:mt-8 mt-[20vh]">
                        <motion.p
                            initial="hidden"
                            whileInView="visible"
                            viewport={{ once: false }}
                            transition={{ duration: 0.3 }}
                            variants={{
                                visible: { opacity: 1, scale: 1 },
                                hidden: { opacity: 0, scale: 0 }
                            }}
                            className="p-[2rem] lg:p-0 text-center lg:text-left  leading-7 text-base tracking-wide font-[aftika-light]">Forget long queues. Forget complicated, hard-to-use coffee machines. You can now simply get your favourite coffee from your smartphone and get an alert when it’s ready for you. More productivity, more bragging rights.</motion.p>
                        <motion.p
                            initial="hidden"
                            whileInView="visible"
                            viewport={{ once: false }}
                            transition={{ duration: 0.3 }}
                            variants={{
                                visible: { opacity: 1, scale: 1 },
                                hidden: { opacity: 0, scale: 0 }
                            }}
                            className="text-center lg:text-left mt-[1rem]  leading-7 text-base tracking-wide font-[aftika-light]">Welcome to the future of work-places.</motion.p>
                        <motion.div

                            initial="hidden"
                            whileInView="visible"
                            viewport={{ once: false }}
                            transition={{ duration: 0.3 }}
                            variants={{
                                visible: { opacity: 1, scale: 1 },
                                hidden: { opacity: 0, scale: 0 }
                            }}
                            className="mt-[2.5rem] lg:px-0 px-[2rem] py-[1rem] lg:py-0 bg-[#000] lg:bg-[#00000000]">
                            <div className="flex mt-[1rem]">
                                <div className="mr-[1rem] flex justify-center items-center ">
                                <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                                </div>
                                <p className="font-normal leading-7 text-base tracking-wide font-[aftika-light]">Ask our expert</p>
                            </div>
                            <div className="flex mt-[1rem]">
                                <div className="mr-[1rem] flex justify-center items-center ">
                                <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                                </div>
                                <p className="font-normal leading-7 text-base tracking-wide font-[aftika-light]">Choose your bundle Or Design your own.</p>
                            </div>
                        </motion.div>
                    </div>
                </div>

            </div>

            {/* page 7 */}
            <div id='climateControl' className="relative lg:min-h-[100vh]">
                {/* desktop image  */}
                <img className="hidden lg:block absolute top-0 left-0 w-full lg:min-h-[100vh] min-h-[50vh] max-h-[50vh] -z-10 object-cover" src="https://syncrow.s3.ap-south-1.amazonaws.com/Mask_Group_46_607c1ffe0b.png" alt="..." />
                {/* mobile image  */}
                <img className="block lg:hidden absolute top-0 left-0 w-full lg:min-h-[100vh] min-h-[60vh] max-h-[60vh] -z-10 object-cover" src="/workspace-page-7-m.png" alt="..." />
                <motion.div
                    initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.3 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}
                    className="text-white text-center h-[40vh] lg:absolute lg:right-[10%] p-[2rem] lg:p-0 lg:bottom-[-10%]">
                    <p style={{ fontFamily: `${guthen}` }} className="lg:text-[4rem] pt-[1rem] lg:pt-0 font-medium">Automated</p>
                    <p className="font-semibold text-[1.5rem] -mt-4">Climate Control. Just Like That.</p>
                </motion.div>
                <div className="flex flex-col lg:pt-[5rem] mt-[25vh] lg:mt-0  lg:w-[40%] lg:pl-[5rem]">
                    <motion.p
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.5 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className="text-center px-[2rem]  leading-7 text-base tracking-wide font-[aftika-light] lg:px-0 lg:text-left">When your office temperature is too hot or cold, it can increase stress and reduce productivity. But when the room temperature is just right, your team is 10x more energetic, and you get more things done. </motion.p>
                    <motion.p
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.5 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className="text-center px-[2rem] lg:px-0 lg:text-left  leading-7 text-base tracking-wide font-[aftika-light]">Smart climate control technology not only maintains the right temperature by intelligently analyzing your usage patterns but also helps you save energy by cutting down the power when it’s not needed.</motion.p>
                    <motion.div
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.5 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className="mt-[2.5rem] lg:px-0 px-[2rem] pb-[2rem] lg:pb-0">
                        <div className="flex mt-[1rem]">
                            <div className="mr-[1rem] flex justify-center items-center">
                            <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                            </div>
                            <p className="font-normal leading-7 text-base tracking-wide font-[aftika-light]">Ask our expert</p>
                        </div>
                        <div className="flex mt-[1rem]">
                            <div className="mr-[1rem] flex justify-center items-center">
                            <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                            </div>
                            <p className="font-normal leading-7 text-base tracking-wide font-[aftika-light]">Choose your bundle Or Design your own.</p>
                        </div>
                    </motion.div>

                </div>


            </div>

            {/* page 8 */}

            <div className="relative flex-col lg:flex mt-[1rem] lg:mt-0 w-[100%] lg:h-[100vh] justify-between lg:overflow-hidden">
                {/* dekstop img  */}
                <img className="hidden lg:block lg:absolute lg:top-0 lg:left-0 w-full h-[50vh] lg:h-full -z-10 object-cover" src="https://syncrow.s3.ap-south-1.amazonaws.com/Mask_Group_33_a29be75c1e.png" alt="..." />
                {/* mobile img  */}
                <img className="block lg:hidden lg:absolute lg:top-0 lg:left-0 w-full h-[40vh] lg:h-full -z-10 object-cover" src="/workspace-page-8-m.png" alt="..." />
                <div className="lg:w-[50%] h-[100%] lg:pl-[10%] px-[2rem] lg:pb-0 -mt-[5vh] pb-[3rem] lg:pt-0 lg:px-0 flex flex-col flex-wrap justify-center">
                    <motion.h3
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.5 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        style={{ fontFamily: `${guthen}` }} className=" font-[aftika-semibold] text-[4.1rem] text-center lg:text-left">Monitor</motion.h3>
                    <motion.h3
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.5 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className=" mb-[2rem] lg:mb-0 font-[aftika-bold] lg:text-[1.7rem] lg:leading-[.8rem] leading-[.6rem] text-center lg:text-left">Workforce. From Anywhere.</motion.h3>
                    <motion.p
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.5 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className="lg:mt-[3rem] text-center lg:text-left  leading-7 text-base tracking-wide font-[aftika-light]">Are you on the go all the time, but want to keep a tab on all the things going around in your workspace? Do you have multiple office locations, and want a simple, easy-to-use app that can monitor everything on your smartphone?</motion.p>
                    <motion.p
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.5 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className="mt-[1rem]  text-center lg:text-left  leading-7 text-base tracking-wide font-[aftika-light]">We’ve got you covered. Our PoE IP infrastructure lets you view, monitor, and track all the ongoing activities in your workplace, from anywhere in the world.</motion.p>

                </div>
            </div>
            {/* page 9 */}
            <div className="relative flex-col lg:flex mt-[1rem] lg:mt-0 w-[100%] min-h-[100vh] lg:justify-center lg:items-end justify-between lg:overflow-hidden">
                {/* dekstop img  */}
                <img className="hidden lg:block absolute top-0 left-0 w-full h-full -z-10 object-cover" src="https://syncrow.s3.ap-south-1.amazonaws.com/Mask_Group_48_59bee67213.png" alt="..." />
                {/* mobile img  */}
                <img className="block lg:hidden absolute top-0 left-0 w-full h-full -z-10 object-cover" src="/workspace-page-9-m.png" alt="..." />
                <div className="lg:w-[50%] lg:px-[4rem] h-[100%] lg:pl-[10%] pt-[50vh] lg:pb-0 pb-[3rem] lg:pt-0 flex flex-col flex-wrap justify-center">
                    <motion.h3
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.5 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        style={{ fontFamily: `${guthen}` }} className=" font-[aftika-semibold] lg:text-[4.1rem] text-[4rem] text-center lg:text-left text-blue-700">Protect</motion.h3>
                    <motion.h3
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.5 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className=" font-[aftika-bold] lg:text-[1.7rem] text-[1.2rem] leading-[1rem] mb-[1rem] lg:mb-0 text-center lg:text-left">Your Employees.</motion.h3>
                    <motion.p
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.5 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className="lg:mt-[3rem] px-[2rem] lg:px-0 text-center lg:text-left  leading-7 text-base tracking-wide font-[aftika-light]">Get instant alerts when there’s a fire, smoke, or flood emergency in your office. Unlike wired alarm systems that don’t get triggered under highly stressful situations, our wireless sensors work in every challenging condition and can even be configured to automatically take pre-defined actions. i.e. call the security, cut-off gas supply, or instantly unlock all the gates in the premises.</motion.p>
                    <motion.div
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.5 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className="mt-[2.5rem] lg:px-0 px-[2rem] pb-[2rem] lg:pb-0">
                        <div className="flex mt-[1rem]">
                            <div className="mr-[1rem] flex justify-center items-center">
                            <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                            </div>
                            <p className="font-normal leading-7 text-base tracking-wide font-[aftika-light]">Ask our expert</p>
                        </div>
                        <div className="flex mt-[1rem]">
                            <div className="mr-[1rem] flex justify-center items-center ">
                            <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                            </div>
                            <p className="font-normal leading-7 text-base tracking-wide font-[aftika-light]">Choose your bundle Or Design your own.</p>
                        </div>
                    </motion.div>

                </div>
            </div>

            {/* page 10 */}
            <div className="relative lg:min-h-[65vh] lg:justify-start">
                <div className="lg:absolute lg:w-[65%] h-[100%] lg:right-0 lg:top-0" >
                    <Lottie options={bulbOptions} />
                </div>
                <div className="lg:pt-[5rem] lg:pl-[5rem] pb-[3rem] flex flex-col justify-center lg:w-[50%]">
                    <motion.h3
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.5 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        style={{ fontFamily: `${guthen}` }} className="px-[2rem] lg:px-0 font-[aftika-sembold] lg:text-[4.1rem] text-[3rem] text-center lg:text-left text-blue-700">Save Energy</motion.h3>
                    <motion.h3
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.5 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className="px-[2rem] font-[aftika-bold] lg:px-0 lg:text-[1.7rem] leading-[1.8rem] text-[1rem] text-center lg:text-left ">With Intelligent Sensing.</motion.h3>
                    <motion.p
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.5 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className="px-[2rem] mt-20 lg:px-0 my-[3rem] text-center lg:text-left leading-7 text-base tracking-wide font-[aftika-light] z-10">Did you know that you can save up to 30% energy costs, just by optimizing switching times and dimming lights when they’re not in use? Establish a green workplace. Intelligently save energy, without compromising on comfort.</motion.p>
                    <motion.div
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: false }}
                        transition={{ duration: 0.5 }}
                        variants={{
                            visible: { opacity: 1, scale: 1 },
                            hidden: { opacity: 0, scale: 0 }
                        }}
                        className="-mt-[1rem] lg:px-0 px-[2rem] pb-[2rem] lg:pb-0">
                        <div className="flex mt-[1rem]">
                            <div className="mr-[1rem] flex justify-center items-center">
                            <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                            </div>
                            <p className="font-normal leading-7 text-base tracking-wide font-[aftika-light]">Ask our expert</p>
                        </div>
                        <div className="flex mt-[1rem]">
                            <div className="mr-[1rem] flex justify-center items-center">
                            <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                            </div>
                            <p className="font-normal leading-7 text-base tracking-wide font-[aftika-light]">Choose your bundle Or Design your own.</p>
                        </div>
                    </motion.div>
                </div>
            </div>
            <Footer />
        </div>
    )
}

export default Workspace;