import Header from "../../components/header";
import Footer from "../../components/footer";
import ContactButtons from "../../components/contactButtons";
import BlueBox from "../../components/blueBox";
import Head from "next/head";
import parse from "html-react-parser";
import Lottie from "react-lottie";
import chatAnimation from "../../pages/lotties/chat.json";
import contactAnimation from "../../pages/lotties/1.json";
import convinienceAnimation from "../../pages/lotties/convinience.json";
import Link from "next/link"
import bulbAnimation from '../lotties/bulb.json';
import batteryAnimation from '../lotties/battery.json';
import energyAnimation from "../lotties/energy-saving.json"
import contactExpertAnimation from "../lotties/ask-your-expert.json"
import {motion} from "framer-motion"


export async function getStaticProps() {
    const res = await fetch(
        "https://syncrow.kodagu.today/api/convenience?populate[0]=page2_cover.media&populate[1]=page4_cover.media"
    );
    const response = await res.json();
    var data = response.data.attributes;
    return {
        props: {
            data,
        },
    };
}

export default function Accessibility({ data }) {
    const guthen = "Guthen Bloots Personal Use";
    const contactExpertOptions = {
        loop: true,
        autoplay: true,
        animationData: contactExpertAnimation,
        renderedSettings: {
            // preserveAspectRatio:'xMidYMid slice'
        },
    };
    const convinienceOptions = {
        loop: true,
        autoplay: true,
        animationData: convinienceAnimation,
        renderedSettings: {
            // preserveAspectRatio:'xMidYMid slice'
        },
    };
    const bulbOptions = {
        loop: true,
        autoplay: true,
        animationData: bulbAnimation,
        rendererSettings: {
          preserveAspectRatio: 'xMidYMid slice',
        },
      };
    //   const energyOptions = {
    //     loop: true,
    //     autoplay: true,
    //     animationData: energyAnimation,
    //     rendererSettings: {
    //       preserveAspectRatio: 'xMidYMid slice',
    //     },
    //   };
    return (
        <div className="overflow-x-hidden">
            <Head>
                <title>Syncrow</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link
                    rel="icon"
                    href="https://ik.imagekit.io/jason7531/syncrow/common/Group_1_rkAObjd65.png?ik-sdk-version=javascript-1.4.3&updatedAt=1642343317149"
                />
                <style>
                    @import
                    url(https://fonts.cdnfonts.com/css/guthen-bloots-personal-use);
                </style>
            </Head>

            {/* page1 */}
            <div className="h-full middle:block hidden" style={{background:"#D9D9D9"}}>
            <Header color="black" /> 
            <div className="flex pt-36 tablet:mx-20 mx-8">
                <div className="pl-10 flex-initial w-5/12">
                <div className=" px-2  text-ft">
                    <div className="laptop:text-base desktop:text-xl tablet:w-11/12">
                        <motion.span
                        initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }} 
                            className="text-5xl laptop:text-7xl desktop:text-7xl text-default"
                            style={{ fontFamily: `${guthen}` }}
                        >
                            {data.page1_title}
                        </motion.span>
                        <br />
                        <motion.p initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}  className="px-10 tablet:px-0 text-tiny tablet:text-lg text-black font-[aftika-light] tracking-wide leading-7">
                        {parse(data.page1_summary)}</motion.p>
                     
                    
                        <br />
               
                         <div className="relative laptop:text-base desktop:text-lg font-normal -mt-10 tablet:mt-0 tablet:-ml-10">
            <div className="flex items-center mb-2">
                <motion.button  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}  >
              
              <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                </motion.button>{" "}
                <Link href="/contact">
                    <motion.span  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className="tablet:absolute tablet:ml-5 top-2 left-16 cursor-pointer text-base tracking-wide leading-7">
                        Ask our Expert
                    </motion.span>
                </Link>
            </div>
            <div className="flex items-center mb-10">
                <motion.button  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}  >
 
 <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                </motion.button>
                <span className="tablet:absolute tablet:ml-5 left-16">
                    <Link href="/bundles">
                        <motion.span  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className="cursor-pointer text-base  tracking-wide leading-7">
                            Choose your bundle
                        </motion.span>
                    </Link>{" "}
                    <motion.span  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className="cursor-pointer text-base tracking-wide leading-7">
                    or{" "}
                        </motion.span>
                    <Link href="/build">
                        <motion.span  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className="cursor-pointer text-base  tracking-wide leading-7">
                            Design your own
                        </motion.span>
                    </Link>
                </span>
            </div>
        </div>
        </div>
        </div>
                </div>
                <div className="flex-1">
                <Lottie
                        options={convinienceOptions}
                      className="w-full h-full"
                    />
                </div>
            </div>
            </div>

            {/* mobile responsive */}
            <div className="h-full middle:hidden block">
                <Header color="white"/>
                <div className="flex flex-col items-center justify-center">
                <div className="flex-1 mt-16 -mb-8 small:mt-32 small:mb-2 flex justify-center items-center w-full">
                    <Lottie
                        options={convinienceOptions}
                        className="w-full border-2 border-blue-500 object-contain"
                        width="160vw"
                        height="40vh"
                    />
                    </div>
                    <div className="flex-1 bg-black text-white">
                    <div className=" px-2  text-center flex items-center justify-center">
                    <div className="laptop:text-base desktop:text-xl small:w-10/12 w-full mt-12">
                    <span
                        className="text-6xl laptop:text-6xl desktop:text-7xl leading-none"
                        style={{ fontFamily: `${guthen}` }}
                    >
                        {data.page1_title}
                    </span>
                    <br />
                    <span className="laptop:text-3xl desktop:text-3xl text-xl font-bold leading-none">
                        {data.page1_subtitle}
                    </span>
                    <br />
                    <br />
                    <br />
                    <p className="px-10 tablet:px-0  font-[aftika-light] tracking-wide leading-7 text-base">
                    {data.page1_summary}</p>
                    <br />
               
                         <div className="relative laptop:text-base desktop:text-lg font-normal mt-2 space-y-2 tablet:mt-0 tablet:-ml-10 mb-4">
            <div className="flex items-center small:mt-0 mt-4">
                <button>
              
                <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                </button>{" "}
                <Link href="/contact">
                    <span className="tablet:absolute tablet:ml-5 ml-2 left-16 cursor-pointer font-[aftika-light] tracking-wide leading-7 text-base text-left">
                        Ask our Expert
                    </span>
                </Link>
            </div>
            <div className="flex items-center tablet:-mt-6 -mt-8">
                <button>
                <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                </button>
                <span className="tablet:absolute tablet:ml-5 left-16 ml-2 text-left">
                    <Link href="/bundles">
                        <span className="cursor-pointer  font-[aftika-light] tracking-wide leading-7 text-base">
                            Choose your bundle
                        </span>
                    </Link>{" "}
                    <span className="cursor-pointer  font-[aftika-light] tracking-wide leading-7 text-base">
                    or{" "}
                        </span>
                    <Link href="/build">
                        <span className="cursor-pointer  font-[aftika-light] tracking-wide leading-7 text-base">
                            Design your own
                        </span>
                    </Link>
                </span>
            </div>
        </div>
        </div>
        </div>
                    </div>
                    
                </div>
            </div>
          
            {/* mobile responsive */}

            {/* page 2*/}

            <div id="climateControl" className="tablet:mx-20 mx-8 flex middle:mb-0 mb-10 middle:mt-12 mt-10 items-center middle:flex-row flex-col">
            <div className="flex-initial w-full small:w-11/12 h-98 laptop:h-100 middle:w-5/12 flex items-end">
                <img src="https://syncrow.s3.ap-south-1.amazonaws.com/shutterstock_1943142007_Cst_Dwn_Owo_67db333c48.webp" className="w-full h-99 object-cover" alt="" />
            </div>
                <div className="flex-1 flex flex-col middle:mt-0 mt-12 middle:items-start items-center">
                    <motion.h1  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className="leading-none"><span className='text-7xl desktop:text-8xl text-default font-thin'
            style={{ fontFamily: `${guthen}` }}>Climate</span></motion.h1>
                    <motion.h1  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className='font-bold tracking-wide -mt-4 text-4xl'>Control</motion.h1>
                    <motion.p  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className=" font-[aftika-light] tracking-wide leading-7 text-base text-black mt-6 middle:text-left text-center">Take comfort to the next level. Track the ambient temperature of your house and change it according to your needs. Command your Air Conditioning system to facilitate optimal cooling or simply stop when you are out of town.
                    <br /><br />
                    <span id="smartLightingPrev">No matter where you are, you can easily control how your home welcomes you back.</span></motion.p>
                </div>
            </div>



      {/* page3 */}


        <div id="smartLighting" className="bg-default tablet:px-20 px-8  pt-10 small:py-20 flex middle:flex-row flex-col-reverse pb-10 items-center">
            <div className="flex-1 flex flex-col text-white middle:pl-20 middle:items-start items-center">
                <motion.h1  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}  ><span className='text-7xl desktop:text-8xl text-white font-thin'
            style={{ fontFamily: `${guthen}` }}>Smart</span></motion.h1>
                <motion.h1  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className='font-semibold tracking-wide -mt-10 text-4xl'>Lightning</motion.h1>
                <motion.p  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className="mt-10  font-[aftika-light] tracking-wide leading-7 text-base middle:text-left text-center">Set the mood just right every time, be it a party or a romantic night-in. Smart lighting solutions allow you to personalize your ambiance and curate personalized schedules.
                <br /><br />
                Accessible from anywhere in the world, smart lighting solutions are automation that adds to the quality of life.</motion.p>
            </div>
            <div className="flex-1 laptop:block hidden">
                <Lottie options={bulbOptions} width={'30vw'} height={'55vh'} />
            </div>
            <div className="flex-1 laptop:hidden block">
                <Lottie options={bulbOptions} width={'80vw'} height={'55vh'} />
            </div>
        </div>


      {/* page 4 */}

        <div id="homeConvenience" className="h-screen w-screen middle:flex items-center justify-end tablet:px-20 px-8 hidden" style={{background:'url(/curtains.jpg)',backgroundRepeat:"no-repeat",backgroundPosition:"center",backgroundSize:"cover"}}>
            <div className="w-1/3">
                <motion.h1  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}  ><span className='text-7xl desktop:text-8xl text-default font-thin'
            style={{ fontFamily: `${guthen}` }}>Smart</span></motion.h1>
                <motion.h1  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className='font-semibold tracking-wide -mt-10 text-4xl'>Curtains</motion.h1>
                <motion.p  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className="mt-6  font-[aftika-light] tracking-wide leading-7 text-base middle:text-left text-center">Control everything in your home through your smartphone or even just by using your voice. Control your curtains and shutters with a pre-set schedule to wake you up to the gentle morning sunlight or to provide much needed shade during the afternoon.
                <br /><br />
                It is the convenience that adds to the beauty of a smarter living experience.</motion.p>
            </div>
        </div>


{/* medium responsive */}

<div id="homeConvenience" className="h-auto middle:hidden flex flex-col items-center justify-end">
<div className="w-screen h-5/12">
    <img src="/Curtains.jpg" width="100%" alt="" />
</div>
            <div className="w-full text-center -mt-16 tablet:px-20 px-8">
                <motion.h1  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}  ><span className='text-7xl desktop:text-8xl text-default font-thin'
            style={{ fontFamily: `${guthen}` }}>Smart</span></motion.h1>
                <motion.h1  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className='font-semibold tracking-wide -mt-10 text-4xl'>Curtains</motion.h1>
                <motion.p  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className="mt-6  font-[aftika-light] tracking-wide leading-7 text-base middle:text-left text-center">Start your day with refreshing natural morning lights or spend your night privately / securely behind closed curtains with a pre-scheduled open and close curtains and shutters.
                <br /><br />
                It is the convenience that adds to the beauty of a smarter living experience.</motion.p>
            </div>
        </div>
{/* medium responsive */}

{/* page 5 */}

<div id="heater" className="h-screen w-screen middle:flex items-center tablet:px-20 px-8 hidden" style={{background:'url(/smart-heater.jpg)',backgroundRepeat:"no-repeat",backgroundPosition:"center",backgroundSize:"cover"}}>
            <div className="w-1/3">
                <motion.h1  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}  ><span className='text-7xl desktop:text-8xl text-default font-thin'
            style={{ fontFamily: `${guthen}` }}>Smart</span></motion.h1>
                <motion.h1  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className='font-semibold tracking-wide -mt-10 text-4xl'>Heaters</motion.h1>
                <motion.p  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className="mt-6  font-[aftika-light] tracking-wide leading-7 text-base middle:text-left text-center">Our Smart water heaters are an advanced type of water heaters that have a wireless connection to your device or an app. These heaters can be controlled via Wi-Fi, that means you can operate the geyser from anywhere and at any time. These advanced water heaters not only monitor water temperature but also utilise those details to minimise energy consumption.
                </motion.p>
            </div>
        </div>


{/* medium responsive */}

<div id="heater" className="h-auto middle:hidden flex flex-col items-center justify-end">
<div className="w-screen h-5/12">
    <img src="/smart-heater.jpg" width="100%" alt="" />
</div>
            <div className="w-full text-center -mt-16 tablet:px-20 px-8">
                <motion.h1  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}  ><span className='text-7xl desktop:text-8xl text-default font-thin'
            style={{ fontFamily: `${guthen}` }}>Smart</span></motion.h1>
                <motion.h1  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className='font-semibold tracking-wide -mt-10 text-4xl'>Heaters</motion.h1>
                <motion.p  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className="mt-6  font-[aftika-light] tracking-wide leading-7 text-base middle:text-left text-center">Our Smart water heaters are an advanced type of water heaters that have a wireless connection to your device or an app. These heaters can be controlled via Wi-Fi, that means you can operate the geyser from anywhere and at any time. These advanced water heaters not only monitor water temperature but also utilise those details to minimise energy consumption.</motion.p>
            </div>
        </div>
{/* medium responsive */}



      {/* page 5 */}



        {/* <div className="tablet:mx-20 mx-8 items-center middle:flex hidden">
            <div className="flex-1 middle:pl-20">
                <motion.h1  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}  ><span className='text-7xl desktop:text-8xl text-default font-thin'
            style={{ fontFamily: `${guthen}` }}>Energy</span></motion.h1>
                <motion.h1  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className='font-semibold tracking-wide -mt-10 text-4xl'>Efficiency</motion.h1>
                <motion.p  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className="mt-6  font-[aftika-light] tracking-wide leading-7 text-base middle:text-left text-center">Smart Home Automation allows everyone to contribute towards a better environment. Our intelligent sensors allow you to save energy whenever you are not at home. And if that’s not enough, you also gain insights into your energy consumption and can personalize schedules accordingly.
                <br /><br />
                Take a step towards a greener lifestyle with intelligent automation.</motion.p>
            </div>
            <div className="flex-initial w-5/12">
            <Lottie options={energyOptions} />
            </div>
        </div>

        <div className="middle:hidden flex flex-col items-center justify-center mt-10 tablet:mx-20 mx-8 pb-10">
            <div>
            <h1><span className='text-7xl desktop:text-8xl text-default font-thin'
            style={{ fontFamily: `${guthen}` }}>Energy</span></h1>
                <h1 className='font-semibold tracking-wide -mt-10 text-4xl'>Efficiency</h1>
            </div>
            <div className="flex-initial w-10/12 tablet:w-7/12">
            <Lottie options={energyOptions} />
            </div>
            <div>
            <p className="mt-6 text-lg tracking-wide font-semibold leading-8 middle:text-left text-center">Smart Home Automation allows everyone to contribute towards a better environment. Our intelligent sensors allow you to save energy whenever you are not at home. And if that’s not enough, you also gain insights into your energy consumption and can personalize schedules accordingly.
                <br /><br />
                Take a step towards a greener lifestyle with intelligent automation.</p>
            </div>
        </div> */}
            
            <Footer />
        </div>
    );
}