import Header from "../../components/header";
import Footer from "../../components/footer";
import ContactButtons from "../../components/contactButtons";
import BlueBox from "../../components/blueBox";
import Head from "next/head";
import phoneAnimation from "../lotties/phone.json";
import exclaimAnimation from "../lotties/exclamation.json";
import Lottie from "react-lottie";
import parse from "html-react-parser";
import chatAnimation from "../../pages/lotties/chat.json";
import contactAnimation from "../../pages/lotties/1.json";
import happinessAnimation from "../../pages/lotties/happinessBegins.json";
import securityAnimation from "../../pages/lotties/security.json";
import Link from "next/link"
import {motion} from "framer-motion"
import contactExpertAnimation from "../../pages/lotties/ask-your-expert.json"

export async function getStaticProps() {
    const res = await fetch(
        "https://syncrow.kodagu.today/api/security?populate[0]=page1_cover.media&populate[1]=page2_cover.media&populate[2]=page3_cover.media"
    );
    const response = await res.json();
    var data = response.data.attributes;
    return {
        props: {
            data,
        },
    };
}

export default function Security({ data }) {
    const guthen = "Guthen Bloots Personal Use";
    const phoneOptions = {
        loop: true,
        autoplay: true,
        animationData: phoneAnimation,
        rendererSettings: {
            preserveAspectRatio: "xMidYMid slice",
        },
    };
    const exclaimOptions = {
        loop: true,
        autoplay: true,
        animationData: exclaimAnimation,
        rendererSettings: {
            preserveAspectRatio: "xMidYMid slice",
        },
    };
    const chatOptions = {
        loop: true,
        autoplay: true,
        animationData: chatAnimation,
        rendererSettings: {
            preserveAspectRatio: "xMidYMid slice",
        },
    };
    const contactOptions = {
        loop: true,
        autoplay: true,
        animationData: contactAnimation,
        renderedSettings: {
            // preserveAspectRatio:'xMidYMid slice'
        },
    };
    const securityOptions = {
        loop: true,
        autoplay: true,
        animationData: securityAnimation,
        renderedSettings: {
            // preserveAspectRatio:'xMidYMid slice'
        },
    };
    const happinessOptions = {
        loop: true,
        autoplay: true,
        animationData: happinessAnimation,
        renderedSettings: {
            // preserveAspectRatio:'xMidYMid slice'
        },
    };
    const contactExpertOptions = {
        loop: true,
        autoplay: true,
        animationData: contactExpertAnimation,
        renderedSettings: {
            // preserveAspectRatio:'xMidYMid slice'
        },
    };
    return (
        <div className="overflow-x-hidden">
            <Head>
                <title>Syncrow</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link
                    rel="icon"
                    href="https://ik.imagekit.io/jason7531/syncrow/common/Group_1_rkAObjd65.png?ik-sdk-version=javascript-1.4.3&updatedAt=1642343317149"
                />
                <style>
                    @import
                    url(https://fonts.cdnfonts.com/css/guthen-bloots-personal-use);
                </style>
            </Head>

            {/* page1 */}
            <div className="h-auto middle:block hidden" style={{background:"#D9D9D9"}}>
            <Header color="black" /> 
            <div className="flex pt-36 medium:mx-20 mx-10">
                <div className="middle:flex-initial middle:w-5/12 flex-1">
                <div className=" px-2  text-ft">
                    <div className="laptop:text-base desktop:text-xl middle:w-11/12 w-full mt-12">
                    <motion.span
                     initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}  
                        className="text-6xl laptop:text-6xl desktop:text-7xl text-default leading-none"
                        style={{ fontFamily: `${guthen}` }}
                    >
                        {data.page1_title}
                    </motion.span>
                    <br />
                    <motion.span  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className="laptop:text-3xl desktop:text-3xl font-bold leading-none">
                        {data.page1_subtitle}
                    </motion.span>
                    <br />
                
                    <motion.p  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className=" font-[aftika-light] tracking-wide leading-7 text-base px-10 tablet:px-0">
                    {data.page1_summary}</motion.p>
                    <br />
               
               
                         <div className="relative laptop:text-base desktop:text-lg font-normal -mt-10 tablet:mt-0">
            <div className="flex items-center mb-2">
                <button>
                <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                </button>{" "}
                <Link href="/contact">
                    <motion.span  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className="tablet:absolute  font-[aftika-light] tracking-wide leading-7 text-base tablet:ml-5 top-2 left-16 cursor-pointer">
                        Ask our Expert
                    </motion.span>
                </Link>
            </div>
            <div className="flex items-center mb-2">
                <button>
 
                <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                </button>
                <motion.span  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className="tablet:absolute tablet:ml-5 left-16">
                    <Link href="/bundles">
                        <span className="cursor-pointer  font-[aftika-light] tracking-wide leading-7 text-base">
                            Choose your bundle
                        </span>
                    </Link>{" "}
                    <span className="cursor-pointer  font-[aftika-light] tracking-wide leading-7 text-base">
                    or{" "}
                        </span>
                    <Link href="/build">
                        <span className="cursor-pointer  font-[aftika-light] tracking-wide leading-7 text-base">
                            Design your own
                        </span>
                    </Link>
                </motion.span>
            </div>
            <br></br>
        </div>
        </div>
        </div>
                </div>
                <div className="flex-1 mt-12">
                <Lottie
                        options={securityOptions}
                        width="40vw"
                        height="50vh"
                    />
                </div>
            </div>
            </div>

            {/* mobile responsive */}
            <div className="h-full middle:hidden block">
                <Header color="white"/>
                <div className="flex flex-col items-center justify-center">
                <div className="flex-1 mt-40 mb-10 flex justify-center items-center">
                    <Lottie
                        options={securityOptions}
                        width="30vw"
                        height="30vh"
                    />
                    </div>
                    <div className="flex-1 bg-black text-white">
                    <div className="  text-center flex items-center justify-center">
                    <div className="laptop:text-base desktop:text-xl small:w-10/12 w-full mt-12">
                    <span
                        className="text-6xl laptop:text-6xl desktop:text-7xl leading-none"
                        style={{ fontFamily: `${guthen}` }}
                    >
                        {data.page1_title}
                    </span>
                    <br />
                    <span className="laptop:text-3xl desktop:text-3xl text-xl font-bold leading-none">
                        {data.page1_subtitle}
                    </span>
                    <br />
                    <br />
                    <br />
                    <p className=" font-[aftika-light] tracking-wide leading-7 text-base px-10 tablet:px-0">
                    {data.page1_summary}</p>
                    <br />
               
                         <div className="relative laptop:text-base space-y-2 desktop:text-lg font-normal -mt-10 tablet:mt-0 tablet:-ml-10 mb-6">
                         <div className="flex items-center small:mt-0 mt-4">
                <button>
              
                <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                </button>{" "}
                <Link href="/contact">
                    <span className="tablet:absolute tablet:ml-5 ml-2 left-16 cursor-pointer font-[aftika-light] tracking-wide leading-7 text-base text-left">
                        Ask our Expert
                    </span>
                </Link>
            </div>
            <div className="flex items-center tablet:-mt-6 -mt-8">
                <button>
                <Lottie
                        options={contactExpertOptions}
                        width={"40px"}
                        height={"40px"}
                    />
                </button>
                <span className="tablet:absolute tablet:ml-5 left-16 ml-2 text-left">
                    <Link href="/bundles">
                        <span className="cursor-pointer  font-[aftika-light] tracking-wide leading-7 text-base">
                            Choose your bundle
                        </span>
                    </Link>{" "}
                    <span className="cursor-pointer  font-[aftika-light] tracking-wide leading-7 text-base">
                    or{" "}
                        </span>
                    <Link href="/build">
                        <span className="cursor-pointer  font-[aftika-light] tracking-wide leading-7 text-base">
                            Design your own
                        </span>
                    </Link>
                </span>
            </div>
        </div>
        </div>
        </div>
                    </div>
                    
                </div>
            </div>
            {/* mobile responsive */}
        
                
            {/* page2 */}

            <div id="intelligence" className="tablet:px-20 px-8 bg-default flex middle:flex-row flex-col items-center">
                <div className="flex-1">
                    <img src="https://syncrow.s3.ap-south-1.amazonaws.com/Mask_Group_32_r5u_Pf_S7_Sa_T_19e5d23a16.png" alt="" />
                </div>
                <div className="flex-1 middle:text-left text-center middle:mb-0 mb-16">
                    <motion.h1  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}  ><span className='text-7xl desktop:text-8xl text-white font-thin'
            style={{ fontFamily: `${guthen}` }}>Intelligent</span></motion.h1>
                    <motion.h1  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className='font-semibold tracking-wide  text-white tablet:-mt-10 -mt-6 text-4xl'>Security</motion.h1>
                    <motion.p  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className=" font-[aftika-light] tracking-wide leading-7 text-base text-white mt-6 middle:text-left text-center">Protect your home from intruders with our intelligent security solutions. Once configured, door/window and motion sensors notify you when someone tries to break into your home when you’re away. As an expansion to the range, we also have wireless doorbells and intelligent locks that provide an additional level of security and mental peace.</motion.p>
                </div>
            </div>
  
            {/* page3 */}
            <div id="monitor" className=" middle:flex hidden w-screen h-100 tablet:px-20 px-8 items-center justify-start pt-20 pb-44" style={{background:'url(https://syncrow.s3.ap-south-1.amazonaws.com/Mask_Group_33_a29be75c1e.png)',backgroundRepeat:"no-repeat",backgroundPosition:"center",backgroundSize:"cover"}}>
                <div className="flex flex-col w-5/12">
                    <motion.h1  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}  ><span className='text-7xl desktop:text-8xl text-black font-thin'
            style={{ fontFamily: `${guthen}` }}>Monitor</span></motion.h1>
                    <motion.p  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className="mt-4  font-[aftika-light] tracking-wide leading-7 text-base text-left ">Keep a tab on your home, even while you’re away in the office or on a vacation. With intelligent CCTV cameras that provide round-the-clock monitoring, staying connected with what matters is easy.
                    <br /><br />
                    The surveillance cameras can be installed standalone or can be configured to secure a covered area.</motion.p>
                </div>
            </div>

            <div className="middle:hidden flex flex-col">
                    <div className="w-screen h-100 tablet:h-102">
                        <img src="/monitor-mobile.png" className="w-screen h-100 tablet:h-102" />
                    </div>
                    <div className="flex flex-col tablet:mx-20 mx-8 items-center justify-center -mt-12">
                    <h1><span className='text-7xl desktop:text-8xl text-black font-thin'
            style={{ fontFamily: `${guthen}` }}>Monitor</span></h1>
                    <p className="mt-4  font-[aftika-light] tracking-wide leading-7 text-base text-center ">Keep a tab on your home, even while you’re away in the office or on a vacation. With intelligent CCTV cameras that provide round-the-clock monitoring, staying connected with what matters is easy.
                    <br /><br />
                    The surveillance cameras can be installed standalone or can be configured to secure a covered area.</p>
                    </div>
            </div>

            {/* page4 */}

            <div id="protection" className="my-10 items-center tablet:mx-20 mx-8 middle:flex hidden">
                <div className="flex-1 -mt-40">
                <Lottie
                    options={phoneOptions}
                    width={"100%"}
                    height="80%"
                
                />
                </div>
                <div className="flex-1 text-left">
                <motion.h1  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}  ><span className='text-7xl desktop:text-8xl text-black font-thin text-left'
            style={{ fontFamily: `${guthen}` }}>Protection</span></motion.h1>
                    <motion.p  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className="mt-4  font-[aftika-light] tracking-wide leading-7 text-base text-left ">Get instant alerts on your smartphone when your home is hit by fire, flood, or any other disaster. You can also configure the central automation system to take corrective action instantly.
                    <br /><br />
                    For eg. Trigger an alarm, turn on the lights to capture attention, or automatically disable all locks in the home for quick evacuation.</motion.p>
                </div>
            </div>


            <div className="middle:hidden flex flex-col tablet:mx-20 mx-8 mt-10">
            <div className="flex-1 flex items-center justify-center">
                <Lottie
                    options={phoneOptions}
                    width={"100%"}
                    height="80%"
                />
                </div>
                <div className="flex-1 text-center mb-10 mt-10 tablet:-mt-56 laptop:-mt-72 z-10">
                <h1><span className='text-7xl desktop:text-8xl text-default font-thin text-center'
            style={{ fontFamily: `${guthen}` }}>Protection</span></h1>
                    <p className="tablet:mt-36  font-[aftika-light] tracking-wide leading-7 text-base text-center ">Get instant alerts on your smartphone when your home is hit by fire, flood, or any other disaster. You can also configure the central automation system to take corrective action instantly.
                    <br /><br />
                    For eg. Trigger an alarm, turn on the lights to capture attention, or automatically disable all locks in the home for quick evacuation.</p>
                </div>
            </div>

            {/* page5 */}
            <div id="doorLock" className=" middle:flex hidden w-screen h-100 tablet:px-20 px-8 items-center justify-start pt-20 pb-44" style={{background:'url(/SmartLock.jpg)',backgroundRepeat:"no-repeat",backgroundPosition:"center",backgroundSize:"cover"}}>
                <div className="flex flex-col w-5/12">
                    <motion.h1  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}  ><span className='text-7xl desktop:text-8xl text-black font-thin'
            style={{ fontFamily: `${guthen}` }}>Smart Lock</span></motion.h1>
                    <motion.p  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className="mt-4  font-[aftika-light] tracking-wide leading-7 text-base text-left ">Use your smartphone instead of the classic key. Control your door with your phone. Maximum convenience without compromising safety. Share digital keys with friends and family and keep track off who has come and gone.</motion.p>
                </div>
            </div>

            <div className="middle:hidden flex flex-col pb-4">
                    <div className="w-screen h-100 tablet:h-102">
                        <img src="/SmartLock.jpg" className="w-screen h-70 tablet:h-102" />
                    </div>
                    <div className="flex flex-col tablet:mx-20 mx-8 items-center justify-center -mt-48">
                    <h1><span className='text-7xl desktop:text-8xl text-black font-thin'
            style={{ fontFamily: `${guthen}` }}>Smart Lock</span></h1>
                    <p className="mt-4  font-[aftika-light] tracking-wide leading-7 text-base text-center ">Use your smartphone instead of the classic key. Control your door with your phone. Maximum convenience without compromising safety. Share digital keys with friends and family and keep track off who has come and gone.</p>
                    </div>
            </div>



            {/* page6 */}
            <div id="happiness" className="py-10 items-center tablet:px-20 bg-cyan-100 px-8 middle:flex hidden">
                <div className="flex-1 -mt-20">
                <Lottie
                    options={happinessOptions}
                    width={"100%"}
                    height="80%"
                
                />
                </div>
                <div className="flex-1 text-left">
                <motion.h1  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}  ><span className='text-7xl desktop:text-8xl text-blue-600 font-thin text-left'
            style={{ fontFamily: `${guthen}` }}>Happiness</span></motion.h1>
           <motion.span  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className="laptop:text-3xl desktop:text-3xl font-bold leading-none">
                        begins with good health
                    </motion.span>
                    <motion.p  initial="hidden"
                    whileInView="visible"
                    viewport={{ once: false }}
                    transition={{ duration: 0.4 }}
                    variants={{
                        visible: { opacity: 1, scale: 1 },
                        hidden: { opacity: 0, scale: 0 }
                    }}   className="mt-4  font-[aftika-light] tracking-wide leading-7 text-base text-left ">Your wellbeing is important to us. Ushering in this new era of preventive health. Now Monitor C02 Levels, humidity and temperature at the palm of your hand. Also monitor and optimise illumination levels.
                    
                    </motion.p>
                </div>
            </div>


            <div className="middle:hidden flex flex-col tablet:px-20 px-8 bg-cyan-100 pt-10">
            <div className="flex-1 flex items-center justify-center">
                <Lottie
                    options={happinessOptions}
                    width={"100%"}
                    height="80%"
                />
                </div>
                <div className="flex-1 text-center mb-10 mt-10 tablet:-mt-56 laptop:-mt-72 z-10">
                <h1><span className='text-7xl desktop:text-8xl text-default font-thin text-center'
            style={{ fontFamily: `${guthen}` }}>Happiness</span></h1>
                <h1><span className='text-3xl desktop:text-8xl font-thin text-center'>begins with good health</span></h1>
                    <p className="tablet:mt-36  font-[aftika-light] tracking-wide leading-7 text-base text-center ">Your wellbeing is important to us. Ushering in this new era of preventive health. Now Monitor C02 Levels, humidity and temperature at the palm of your hand. Also monitor and optimise illumination levels.</p>
                </div>
            </div>
            <Footer />
        </div>
    );
}